<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Giro;
use App\Models\User;

class GiroSeeder extends Seeder
{
    public function run(): void
    {
        $columns = ['id'];
        $users = User::all($columns);

        $nuevosGiros = [
            ['nombre' => 'Sin actividad económica', 'codigo_mh' => ''],
            ['nombre' => 'Cultivo de cereales excepto arroz y para forrajes', 'codigo_mh' => '01111'],
            ['nombre' => 'Cultivo de legumbres', 'codigo_mh' => '01112'],
            ['nombre' => 'Cultivo de semillas oleaginosas', 'codigo_mh' => '01113'],
            ['nombre' => 'Cultivo de plantas para la preparación de semillas', 'codigo_mh' => '01114'],
            ['nombre' => 'Cultivo de otros cereales excepto arroz y forrajeros n.c.p.', 'codigo_mh' => '01119'],
            ['nombre' => 'Cultivo de arroz', 'codigo_mh' => '01120'],
            ['nombre' => 'Cultivo de raíces y tubérculos', 'codigo_mh' => '01131'],
            ['nombre' => 'Cultivo de brotes, bulbos, vegetales tubérculos y cultivos similares', 'codigo_mh' => '01132'],
            ['nombre' => 'Cultivo hortícola de fruto', 'codigo_mh' => '01133'],
            ['nombre' => 'Cultivo de hortalizas de hoja y otras hortalizas ncp', 'codigo_mh' => '01134'],
            ['nombre' => 'Cultivo de caña de azúcar', 'codigo_mh' => '01140'],
            ['nombre' => 'Cultivo de tabaco', 'codigo_mh' => '01150'],
            ['nombre' => 'Cultivo de algodón', 'codigo_mh' => '01161'],
            ['nombre' => 'Cultivo de fibras vegetales excepto algodón', 'codigo_mh' => '01162'],
            ['nombre' => 'Cultivo de plantas no perennes para la producción de semillas y flores', 'codigo_mh' => '01191'],
            ['nombre' => 'Cultivo de cereales y pastos para la alimentación animal', 'codigo_mh' => '01192'],
            ['nombre' => 'Producción de cultivos no estacionales ncp', 'codigo_mh' => '01199'],
            ['nombre' => 'Cultivo de frutas tropicales', 'codigo_mh' => '01220'],
            ['nombre' => 'Cultivo de cítricos', 'codigo_mh' => '01230'],
            ['nombre' => 'Cultivo de frutas de pepita y hueso', 'codigo_mh' => '01240'],
            ['nombre' => 'Cultivo de frutas ncp', 'codigo_mh' => '01251'],
            ['nombre' => 'Cultivo de otros frutos y nueces de árboles y arbustos', 'codigo_mh' => '01252'],
            ['nombre' => 'Cultivo de frutos oleaginosos', 'codigo_mh' => '01260'],
            ['nombre' => 'Cultivo de café', 'codigo_mh' => '01271'],
            ['nombre' => 'Cultivo de plantas para la elaboración de bebidas excepto café', 'codigo_mh' => '01272'],
            ['nombre' => 'Cultivo de especias y aromáticas', 'codigo_mh' => '01281'],
            ['nombre' => 'Cultivo de plantas para la obtención de productos medicinales y farmacéuticos', 'codigo_mh' => '01282'],
            ['nombre' => 'Cultivo de árboles de hule (caucho) para la obtención de látex', 'codigo_mh' => '01291'],
            ['nombre' => 'Cultivo de plantas para la obtención de productos químicos y colorantes', 'codigo_mh' => '01292'],
            ['nombre' => 'Producción de cultivos perennes ncp', 'codigo_mh' => '01299'],
            ['nombre' => 'Propagación de plantas', 'codigo_mh' => '01300'],
            ['nombre' => 'Cultivo de plantas y flores ornamentales', 'codigo_mh' => '01301'],
            ['nombre' => 'Cría y engorde de ganado bovino', 'codigo_mh' => '01410'],
            ['nombre' => 'Cría de caballos y otros equinos', 'codigo_mh' => '01420'],
            ['nombre' => 'Cría de ovejas y cabras', 'codigo_mh' => '01440'],
            ['nombre' => 'Cría de cerdos', 'codigo_mh' => '01450'],
            ['nombre' => 'Cría de aves de corral y producción de huevos', 'codigo_mh' => '01460'],
            ['nombre' => 'Cría de abejas apicultura para la obtención de miel y otros productos apícolas', 'codigo_mh' => '01491'],
            ['nombre' => 'Cría de conejos', 'codigo_mh' => '01492'],
            ['nombre' => 'Cría de iguanas y garrobos', 'codigo_mh' => '01493'],
            ['nombre' => 'Cría de mariposas y otros insectos', 'codigo_mh' => '01494'],
            ['nombre' => 'Cría y obtención de productos animales n.c.p.', 'codigo_mh' => '01499'],
            ['nombre' => 'Cultivo de productos agrícolas en combinación con la cría de animales', 'codigo_mh' => '01500'],
            ['nombre' => 'Servicios de maquinaria agrícola', 'codigo_mh' => '01611'],
            ['nombre' => 'Control de plagas', 'codigo_mh' => '01612'],
            ['nombre' => 'Servicios de riego', 'codigo_mh' => '01613'],
            ['nombre' => 'Servicios de contratación de mano de obra para la agricultura', 'codigo_mh' => '01614'],
            ['nombre' => 'Servicios agrícolas ncp', 'codigo_mh' => '01619'],
            ['nombre' => 'Actividades para mejorar la reproducción, el crecimiento y el rendimiento de los animales y sus productos', 'codigo_mh' => '01621'],
            ['nombre' => 'Servicios de mano de obra pecuaria', 'codigo_mh' => '01622'],
            ['nombre' => 'Servicios pecuarios ncp', 'codigo_mh' => '01629'],
            ['nombre' => 'Labores post cosecha de preparación de los productos agrícolas para su comercialización o para la industria', 'codigo_mh' => '01631'],
            ['nombre' => 'Servicio de beneficio de café', 'codigo_mh' => '01632'],
            ['nombre' => 'Servicio de beneficiado de plantas textiles (incluye el beneficiado cuando este es realizado en la misma explotación agropecuaria)', 'codigo_mh' => '01633'],
            ['nombre' => 'Tratamiento de semillas para la propagación', 'codigo_mh' => '01640'],
            ['nombre' => 'Caza ordinaria y mediante trampas, repoblación de animales de caza y servicios conexos', 'codigo_mh' => '01700'],
            ['nombre' => 'Silvicultura y otras actividades forestales', 'codigo_mh' => '02100'],
            ['nombre' => 'Extracción de madera', 'codigo_mh' => '02200'],
            ['nombre' => 'Recolección de productos diferentes a la madera', 'codigo_mh' => '02300'],
            ['nombre' => 'Servicios de apoyo a la silvicultura', 'codigo_mh' => '02400'],
            ['nombre' => 'Pesca marítima de altura y costera', 'codigo_mh' => '03110'],
            ['nombre' => 'Pesca de agua dulce', 'codigo_mh' => '03120'],
            ['nombre' => 'Acuicultura marítima', 'codigo_mh' => '03210'],
            ['nombre' => 'Acuicultura de agua dulce', 'codigo_mh' => '03220'],
            ['nombre' => 'Servicios de apoyo a la pesca y acuicultura', 'codigo_mh' => '03300'],
            ['nombre' => 'Extracción de hulla', 'codigo_mh' => '05100'],
            ['nombre' => 'Extracción y aglomeración de lignito', 'codigo_mh' => '05200'],
            ['nombre' => 'Extracción de petróleo crudo', 'codigo_mh' => '06100'],
            ['nombre' => 'Extracción de gas natural', 'codigo_mh' => '06200'],
            ['nombre' => 'Extracción de minerales de hierro', 'codigo_mh' => '07100'],
            ['nombre' => 'Extracción de minerales de uranio y torio', 'codigo_mh' => '07210'],
            ['nombre' => 'Extracción de minerales metalíferos no ferrosos', 'codigo_mh' => '07290'],
            ['nombre' => 'Extracción de piedra, arena y arcilla', 'codigo_mh' => '08100'],
            ['nombre' => 'Extracción de minerales para la fabricación de abonos y productos químicos', 'codigo_mh' => '08910'],
            ['nombre' => 'Extracción y aglomeración de turba', 'codigo_mh' => '08920'],
            ['nombre' => 'Extracción de sal', 'codigo_mh' => '08930'],
            ['nombre' => 'Explotación de otras minas y canteras ncp', 'codigo_mh' => '08990'],
            ['nombre' => 'Actividades de apoyo a la extracción de petróleo y gas natural', 'codigo_mh' => '09100'],
            ['nombre' => 'Actividades de apoyo a la explotación de minas y canteras', 'codigo_mh' => '09900'],
            ['nombre' => 'Servicio de rastros y mataderos de bovinos y porcinos', 'codigo_mh' => '10101'],
            ['nombre' => 'Matanza y procesamiento de bovinos y porcinos', 'codigo_mh' => '10102'],
            ['nombre' => 'Matanza y procesamientos de aves de corral', 'codigo_mh' => '10103'],
            ['nombre' => 'Elaboración y conservación de embutidos y tripas naturales', 'codigo_mh' => '10104'],
            ['nombre' => 'Servicios de conservación y empaque de carnes', 'codigo_mh' => '10105'],
            ['nombre' => 'Elaboración y conservación de grasas y aceites animales', 'codigo_mh' => '10106'],
            ['nombre' => 'Servicios de molienda de carne', 'codigo_mh' => '10107'],
            ['nombre' => 'Elaboración de productos de carne ncp', 'codigo_mh' => '10108'],
            ['nombre' => 'Procesamiento y conservación de pescado, crustáceos y moluscos', 'codigo_mh' => '10201'],
            ['nombre' => 'Fabricación de productos de pescado ncp', 'codigo_mh' => '10209'],
            ['nombre' => 'Elaboración de jugos de frutas y hortalizas', 'codigo_mh' => '10301'],
            ['nombre' => 'Elaboración y envase de jaleas, mermeladas y frutas deshidratadas', 'codigo_mh' => '10302'],
            ['nombre' => 'Elaboración de productos de frutas y hortalizas n.c.p.', 'codigo_mh' => '10309'],
            ['nombre' => 'Fabricación de aceites y grasas vegetales y animales comestibles', 'codigo_mh' => '10401'],
            ['nombre' => 'Fabricación de aceites y grasas vegetales y animales no comestibles', 'codigo_mh' => '10402'],
            ['nombre' => 'Servicio de maquilado de aceites', 'codigo_mh' => '10409'],
            ['nombre' => 'Fabricación de productos lácteos excepto sorbetes y quesos sustitutos', 'codigo_mh' => '10501'],
            ['nombre' => 'Fabricación de sorbetes y helados', 'codigo_mh' => '10502'],
            ['nombre' => 'Fabricación de quesos', 'codigo_mh' => '10503'],
            ['nombre' => 'Molienda de cereales', 'codigo_mh' => '10611'],
            ['nombre' => 'Elaboración de cereales para el desayuno y similares', 'codigo_mh' => '10612'],
            ['nombre' => 'Servicios de beneficiado de productos agrícolas ncp (excluye Beneficio de azúcar rama 1072 y beneficio de café rama 0163)', 'codigo_mh' => '10613'],
            ['nombre' => 'Fabricación de almidón', 'codigo_mh' => '10621'],
            ['nombre' => 'Servicio de molienda de maíz húmedo molino para nixtamal', 'codigo_mh' => '10628'],
            ['nombre' => 'Elaboración de tortillas', 'codigo_mh' => '10711'],
            ['nombre' => 'Fabricación de pan, galletas y barquillos', 'codigo_mh' => '10712'],
            ['nombre' => 'Fabricación de repostería', 'codigo_mh' => '10713'],
            ['nombre' => 'Ingenios azucareros', 'codigo_mh' => '10721'],
            ['nombre' => 'Molienda de caña de azúcar para la elaboración de dulces', 'codigo_mh' => '10722'],
            ['nombre' => 'Elaboración de jarabes de azúcar y otros similares', 'codigo_mh' => '10723'],
            ['nombre' => 'Maquilado de azúcar de caña', 'codigo_mh' => '10724'],
            ['nombre' => 'Fabricación de cacao, chocolates y productos de confitería', 'codigo_mh' => '10730'],
            ['nombre' => 'Elaboración de macarrones, fideos, y productos farináceos similares', 'codigo_mh' => '10740'],
            ['nombre' => 'Elaboración de comidas y platos preparados para la reventa en locales y/o para exportación', 'codigo_mh' => '10750'],
            ['nombre' => 'Elaboración de productos de café', 'codigo_mh' => '10791'],
            ['nombre' => 'Elaboración de especias, sazonadores y condimentos', 'codigo_mh' => '10792'],
            ['nombre' => 'Elaboración de sopas, cremas y consomé', 'codigo_mh' => '10793'],
            ['nombre' => 'Fabricación de bocadillos tostados y/o fritos', 'codigo_mh' => '10794'],
            ['nombre' => 'Elaboración de productos alimenticios ncp', 'codigo_mh' => '10799'],
            ['nombre' => 'Elaboración de alimentos preparados para animales', 'codigo_mh' => '10800'],
            ['nombre' => 'Fabricación de aguardiente y licores', 'codigo_mh' => '11012'],
            ['nombre' => 'Elaboración de vinos', 'codigo_mh' => '11020'],
            ['nombre' => 'Fabricación de cerveza', 'codigo_mh' => '11030'],
            ['nombre' => 'Fabricación de aguas gaseosas', 'codigo_mh' => '11041'],
            ['nombre' => 'Fabricación y envasado de agua', 'codigo_mh' => '11042'],
            ['nombre' => 'Elaboración de refrescos', 'codigo_mh' => '11043'],
            ['nombre' => 'Maquilado de aguas gaseosas', 'codigo_mh' => '11048'],
            ['nombre' => 'Elaboración de bebidas no alcohólicas', 'codigo_mh' => '11049'],
            ['nombre' => 'Elaboración de productos de tabaco', 'codigo_mh' => '12000'],
            ['nombre' => 'Preparación de fibras textiles', 'codigo_mh' => '13111'],
            ['nombre' => 'Fabricación de hilados', 'codigo_mh' => '13112'],
            ['nombre' => 'Fabricación de telas', 'codigo_mh' => '13120'],
            ['nombre' => 'Acabado de productos textiles', 'codigo_mh' => '13130'],
            ['nombre' => 'Fabricación de tejidos de punto y ganchillo', 'codigo_mh' => '13910'],
            ['nombre' => 'Fabricación de productos textiles para el hogar', 'codigo_mh' => '13921'],
            ['nombre' => 'Sacos, bolsas y otros artículos textiles', 'codigo_mh' => '13922'],
            ['nombre' => 'Fabricación de artículos confeccionados con materiales textiles, excepto prendas de vestir ncp', 'codigo_mh' => '13929'],
            ['nombre' => 'Fabricación de tapices y alfombras', 'codigo_mh' => '13930'],
            ['nombre' => 'Fabricación de cuerdas de henequén y otras fibras naturales (lazos, pitas)', 'codigo_mh' => '13941'],
            ['nombre' => 'Fabricación de redes de diversos materiales', 'codigo_mh' => '13942'],
            ['nombre' => 'Maquilado de productos trenzables de cualquier material (petates, sillas, etc.)', 'codigo_mh' => '13948'],
            ['nombre' => 'Fabricación de adornos, etiquetas y otros artículos para prendas de vestir', 'codigo_mh' => '13991'],
            ['nombre' => 'Servicio de bordados en artículos y prendas de tela', 'codigo_mh' => '13992'],
            ['nombre' => 'Fabricación de productos textiles ncp', 'codigo_mh' => '13999'],
            ['nombre' => 'Fabricación de ropa interior, para dormir y similares', 'codigo_mh' => '14101'],
            ['nombre' => 'Fabricación de ropa para niños', 'codigo_mh' => '14102'],
            ['nombre' => 'Fabricación de prendas de vestir para ambos sexos', 'codigo_mh' => '14103'],
            ['nombre' => 'Confección de prendas a medida', 'codigo_mh' => '14104'],
            ['nombre' => 'Fabricación de prendas de vestir para deportes', 'codigo_mh' => '14105'],
            ['nombre' => 'Elaboración de artesanías de uso personal confeccionadas especialmente de materiales textiles', 'codigo_mh' => '14106'],
            ['nombre' => 'Maquilado de prendas de vestir, accesorios y otros', 'codigo_mh' => '14108'],
            ['nombre' => 'Fabricación de prendas y accesorios de vestir n.c.p.', 'codigo_mh' => '14109'],
            ['nombre' => 'Fabricación de artículos de piel', 'codigo_mh' => '14200'],
            ['nombre' => 'Fabricación de calcetines, calcetas, medias (panty house) y otros similares', 'codigo_mh' => '14301'],
            ['nombre' => 'Fabricación de ropa interior de tejido de punto', 'codigo_mh' => '14302'],
            ['nombre' => 'Fabricación de prendas de vestir de tejido de punto ncp', 'codigo_mh' => '14309'],
            ['nombre' => 'Curtido y adobo de cueros; adobo y teñido de pieles', 'codigo_mh' => '15110'],
            ['nombre' => 'Fabricación de maletas, bolsos de mano y otros artículos de marroquinería', 'codigo_mh' => '15121'],
            ['nombre' => 'Fabricación de monturas, accesorios y vainas talabartería', 'codigo_mh' => '15122'],
            ['nombre' => 'Fabricación de artesanías principalmente de cuero natural y sintético', 'codigo_mh' => '15123'],
            ['nombre' => 'Maquilado de artículos de cuero natural, sintético y de otros materiales', 'codigo_mh' => '15128'],
            ['nombre' => 'Fabricación de calzado', 'codigo_mh' => '15201'],
            ['nombre' => 'Fabricación de partes y accesorios de calzado', 'codigo_mh' => '15202'],
            ['nombre' => 'Maquilado de partes y accesorios de calzado', 'codigo_mh' => '15208'],
            ['nombre' => 'Aserradero y acepilladura de madera', 'codigo_mh' => '16100'],
            ['nombre' => 'Fabricación de madera laminada, terciada, enchapada y contrachapada, paneles para la construcción', 'codigo_mh' => '16210'],
            ['nombre' => 'Fabricación de partes y piezas de carpintería para edificios y construcciones', 'codigo_mh' => '16220'],
            ['nombre' => 'Fabricación de envases y recipientes de madera', 'codigo_mh' => '16230'],
            ['nombre' => 'Fabricación de artesanías de madera, semillas, materiales trenzables', 'codigo_mh' => '16292'],
            ['nombre' => 'Fabricación de productos de madera, corcho, paja y materiales trenzables ncp', 'codigo_mh' => '16299'],
            ['nombre' => 'Fabricación de pasta de madera, papel y cartón', 'codigo_mh' => '17010'],
            ['nombre' => 'Fabricación de papel y cartón ondulado y envases de papel y cartón', 'codigo_mh' => '17020'],
            ['nombre' => 'Fabricación de artículos de papel y cartón de uso personal y doméstico', 'codigo_mh' => '17091'],
            ['nombre' => 'Fabricación de productos de papel ncp', 'codigo_mh' => '17092'],
            ['nombre' => 'Impresión', 'codigo_mh' => '18110'],
            ['nombre' => 'Servicios relacionados con la impresión', 'codigo_mh' => '18120'],
            ['nombre' => 'Reproducción de grabaciones', 'codigo_mh' => '18200'],
            ['nombre' => 'Fabricación de productos de hornos de coque', 'codigo_mh' => '19100'],
            ['nombre' => 'Fabricación de combustible', 'codigo_mh' => '19201'],
            ['nombre' => 'Fabricación de aceites y lubricantes', 'codigo_mh' => '19202'],
            ['nombre' => 'Fabricación de materias primas para la fabricación de colorantes', 'codigo_mh' => '20111'],
            ['nombre' => 'Fabricación de materiales curtientes', 'codigo_mh' => '20112'],
            ['nombre' => 'Fabricación de gases industriales', 'codigo_mh' => '20113'],
            ['nombre' => 'Fabricación de alcohol etílico', 'codigo_mh' => '20114'],
            ['nombre' => 'Fabricación de sustancias químicas básicas', 'codigo_mh' => '20119'],
            ['nombre' => 'Fabricación de abonos y fertilizantes', 'codigo_mh' => '20120'],
            ['nombre' => 'Fabricación de plástico y caucho en formas primarias', 'codigo_mh' => '20130'],
            ['nombre' => 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario', 'codigo_mh' => '20210'],
            ['nombre' => 'Fabricación de pinturas, barnices y productos de revestimiento similares; tintas de imprenta y masillas', 'codigo_mh' => '20220'],
            ['nombre' => 'Fabricación de jabones, detergentes y similares para limpieza', 'codigo_mh' => '20231'],
            ['nombre' => 'Fabricación de perfumes, cosméticos y productos de higiene y cuidado personal, incluyendo tintes, champú, etc.', 'codigo_mh' => '20232'],
            ['nombre' => 'Fabricación de tintas y colores para escribir y pintar; fabricación de cintas para impresoras', 'codigo_mh' => '20291'],
            ['nombre' => 'Fabricación de productos pirotécnicos, explosivos y municiones', 'codigo_mh' => '20292'],
            ['nombre' => 'Fabricación de productos químicos n.c.p.', 'codigo_mh' => '20299'],
            ['nombre' => 'Fabricación de fibras artificiales', 'codigo_mh' => '20300'],
            ['nombre' => 'Manufactura de productos farmacéuticos, sustancias químicas y productos botánicos', 'codigo_mh' => '21001'],
            ['nombre' => 'Maquilado de medicamentos', 'codigo_mh' => '21008'],
            ['nombre' => 'Fabricación de cubiertas y cámaras; renovación y recauchutado de cubiertas', 'codigo_mh' => '22110'],
            ['nombre' => 'Fabricación de otros productos de caucho', 'codigo_mh' => '22190'],
            ['nombre' => 'Fabricación de envases plásticos', 'codigo_mh' => '22201'],
            ['nombre' => 'Fabricación de productos plásticos para uso personal o doméstico', 'codigo_mh' => '22202'],
            ['nombre' => 'Maquila de plásticos', 'codigo_mh' => '22208'],
            ['nombre' => 'Fabricación de productos plásticos n.c.p.', 'codigo_mh' => '22209'],
            ['nombre' => 'Fabricación de vidrio', 'codigo_mh' => '23101'],
            ['nombre' => 'Fabricación de recipientes y envases de vidrio', 'codigo_mh' => '23102'],
            ['nombre' => 'Servicio de maquilado', 'codigo_mh' => '23108'],
            ['nombre' => 'Fabricación de productos de vidrio ncp', 'codigo_mh' => '23109'],
            ['nombre' => 'Fabricación de productos refractarios', 'codigo_mh' => '23910'],
            ['nombre' => 'Fabricación de productos de arcilla para la construcción', 'codigo_mh' => '23920'],
            ['nombre' => 'Fabricación de productos de cerámica y porcelana no refractaria', 'codigo_mh' => '23931'],
            ['nombre' => 'Fabricación de productos de cerámica y porcelana ncp', 'codigo_mh' => '23932'],
            ['nombre' => 'Fabricación de cemento, cal y yeso', 'codigo_mh' => '23940'],
            ['nombre' => 'Fabricación de artículos de hormigón, cemento y yeso', 'codigo_mh' => '23950'],
            ['nombre' => 'Corte, tallado y acabado de la piedra', 'codigo_mh' => '23960'],
            ['nombre' => 'Fabricación de productos minerales no metálicos ncp', 'codigo_mh' => '23990'],
            ['nombre' => 'Industrias básicas de hierro y acero', 'codigo_mh' => '24100'],
            ['nombre' => 'Fabricación de productos primarios de metales preciosos y metales no ferrosos', 'codigo_mh' => '24200'],
            ['nombre' => 'Fundición de hierro y acero', 'codigo_mh' => '24310'],
            ['nombre' => 'Fundición de metales no ferrosos', 'codigo_mh' => '24320'],
            ['nombre' => 'Fabricación de productos metálicos para uso estructural', 'codigo_mh' => '25111'],
            ['nombre' => 'Servicio de maquila para la fabricación de estructuras metálicas', 'codigo_mh' => '25118'],
            ['nombre' => 'Fabricación de tanques, depósitos y recipientes de metal', 'codigo_mh' => '25120'],
            ['nombre' => 'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central', 'codigo_mh' => '25130'],
            ['nombre' => 'Fabricación de armas y municiones', 'codigo_mh' => '25200'],
            ['nombre' => 'Forjado, prensado, estampado y laminado de metales; pulvimetalurgia', 'codigo_mh' => '25910'],
            ['nombre' => 'Tratamiento y revestimiento de metales', 'codigo_mh' => '25920'],
            ['nombre' => 'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería', 'codigo_mh' => '25930'],
            ['nombre' => 'Fabricación de envases y artículos conexos de metal', 'codigo_mh' => '25991'],
            ['nombre' => 'Fabricación de artículos metálicos de uso personal y/o doméstico', 'codigo_mh' => '25992'],
            ['nombre' => 'Fabricación de productos elaborados de metal ncp', 'codigo_mh' => '25999'],
            ['nombre' => 'Fabricación de componentes electrónicos', 'codigo_mh' => '26100'],
            ['nombre' => 'Fabricación de computadoras y equipo conexo', 'codigo_mh' => '26200'],
            ['nombre' => 'Fabricación de equipo de comunicaciones', 'codigo_mh' => '26300'],
            ['nombre' => 'Fabricación de aparatos electrónicos de consumo para audio, video radio y televisión', 'codigo_mh' => '26400'],
            ['nombre' => 'Fabricación de instrumentos y aparatos para medir, verificar, ensayar, navegar y de control de procesos industriales', 'codigo_mh' => '26510'],
            ['nombre' => 'Fabricación de relojes y piezas de relojes', 'codigo_mh' => '26520'],
            ['nombre' => 'Fabricación de equipo médico de irradiación y equipo electrónico de uso médico y terapéutico', 'codigo_mh' => '26600'],
            ['nombre' => 'Fabricación de instrumentos de óptica y equipo fotográfico', 'codigo_mh' => '26700'],
            ['nombre' => 'Fabricación de medios magnéticos y ópticos', 'codigo_mh' => '26800'],
            ['nombre' => 'Fabricación de motores, generadores, transformadores eléctricos, aparatos de distribución y control de electricidad', 'codigo_mh' => '27100'],
            ['nombre' => 'Fabricación de pilas, baterías y acumuladores', 'codigo_mh' => '27200'],
            ['nombre' => 'Fabricación de cables de fibra óptica', 'codigo_mh' => '27310'],
            ['nombre' => 'Fabricación de otros hilos y cables eléctricos', 'codigo_mh' => '27320'],
            ['nombre' => 'Fabricación de dispositivos de cableados', 'codigo_mh' => '27330'],
            ['nombre' => 'Fabricación de equipo eléctrico de iluminación', 'codigo_mh' => '27400'],
            ['nombre' => 'Fabricación de aparatos de uso doméstico', 'codigo_mh' => '27500'],
            ['nombre' => 'Fabricación de otros tipos de equipo eléctrico', 'codigo_mh' => '27900'],
            ['nombre' => 'Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas', 'codigo_mh' => '28110'],
            ['nombre' => 'Fabricación de equipo hidráulico', 'codigo_mh' => '28120'],
            ['nombre' => 'Fabricación de otras bombas, compresores, grifos y válvulas', 'codigo_mh' => '28130'],
            ['nombre' => 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión', 'codigo_mh' => '28140'],
            ['nombre' => 'Fabricación de hornos y quemadores', 'codigo_mh' => '28150'],
            ['nombre' => 'Fabricación de equipo de elevación y manipulación', 'codigo_mh' => '28160'],
            ['nombre' => 'Fabricación de maquinaria y equipo de oficina', 'codigo_mh' => '28170'],
            ['nombre' => 'Fabricación de herramientas manuales', 'codigo_mh' => '28180'],
            ['nombre' => 'Fabricación de otros tipos de maquinaria de uso general', 'codigo_mh' => '28190'],
            ['nombre' => 'Fabricación de maquinaria agropecuaria y forestal', 'codigo_mh' => '28210'],
            ['nombre' => 'Fabricación de máquinas para conformar metales y maquinaria herramienta', 'codigo_mh' => '28220'],
            ['nombre' => 'Fabricación de maquinaria metalúrgica', 'codigo_mh' => '28230'],
            ['nombre' => 'Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción', 'codigo_mh' => '28240'],
            ['nombre' => 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco', 'codigo_mh' => '28250'],
            ['nombre' => 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros', 'codigo_mh' => '28260'],
            ['nombre' => 'Fabricación de máquinas para imprenta', 'codigo_mh' => '28291'],
            ['nombre' => 'Fabricación de maquinaria de uso especial ncp', 'codigo_mh' => '28299'],
            ['nombre' => 'Fabricación vehículos automotores', 'codigo_mh' => '29100'],
            ['nombre' => 'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semiremolques', 'codigo_mh' => '29200'],
            ['nombre' => 'Fabricación de partes, piezas y accesorios para vehículos automotores', 'codigo_mh' => '29300'],
            ['nombre' => 'Fabricación de buques', 'codigo_mh' => '30110'],
            ['nombre' => 'Construcción y reparación de embarcaciones de recreo', 'codigo_mh' => '30120'],
            ['nombre' => 'Fabricación de locomotoras y de material rodante', 'codigo_mh' => '30200'],
            ['nombre' => 'Fabricación de aeronaves y naves espaciales', 'codigo_mh' => '30300'],
            ['nombre' => 'Fabricación de vehículos militares de combate', 'codigo_mh' => '30400'],
            ['nombre' => 'Fabricación de motocicletas', 'codigo_mh' => '30910'],
            ['nombre' => 'Fabricación de bicicletas y sillones de ruedas para inválidos', 'codigo_mh' => '30920'],
            ['nombre' => 'Fabricación de equipo de transporte ncp', 'codigo_mh' => '30990'],
            ['nombre' => 'Fabricación de colchones y somier', 'codigo_mh' => '31001'],
            ['nombre' => 'Fabricación de muebles y otros productos de madera a medida', 'codigo_mh' => '31002'],
            ['nombre' => 'Servicios de maquilado de muebles', 'codigo_mh' => '31008'],
            ['nombre' => 'Fabricación de muebles ncp', 'codigo_mh' => '31009'],
            ['nombre' => 'Fabricación de joyas platerías y joyerías', 'codigo_mh' => '32110'],
            ['nombre' => 'Fabricación de joyas de imitación (fantasía) y artículos conexos', 'codigo_mh' => '32120'],
            ['nombre' => 'Fabricación de instrumentos musicales', 'codigo_mh' => '32200'],
            ['nombre' => 'Fabricación de artículos de deporte', 'codigo_mh' => '32301'],
            ['nombre' => 'Servicio de maquila de productos deportivos', 'codigo_mh' => '32308'],
            ['nombre' => 'Fabricación de juegos de mesa y de salón', 'codigo_mh' => '32401'],
            ['nombre' => 'Servicio de maquilado de juguetes y juegos', 'codigo_mh' => '32402'],
            ['nombre' => 'Fabricación de juegos y juguetes n.c.p.', 'codigo_mh' => '32409'],
            ['nombre' => 'Fabricación de instrumentos y materiales médicos y odontológicos', 'codigo_mh' => '32500'],
            ['nombre' => 'Fabricación de lápices, bolígrafos, sellos y artículos de librería en general', 'codigo_mh' => '32901'],
            ['nombre' => 'Fabricación de escobas, cepillos, pinceles y similares', 'codigo_mh' => '32902'],
            ['nombre' => 'Fabricación de artesanías de materiales diversos', 'codigo_mh' => '32903'],
            ['nombre' => 'Fabricación de artículos de uso personal y domésticos n.c.p.', 'codigo_mh' => '32904'],
            ['nombre' => 'Fabricación de accesorios para las confecciones y la marroquinería n.c.p.', 'codigo_mh' => '32905'],
            ['nombre' => 'Servicios de maquila ncp', 'codigo_mh' => '32908'],
            ['nombre' => 'Fabricación de productos manufacturados n.c.p.', 'codigo_mh' => '32909'],
            ['nombre' => 'Reparación y mantenimiento de productos elaborados de metal', 'codigo_mh' => '33110'],
            ['nombre' => 'Reparación y mantenimiento de maquinaria', 'codigo_mh' => '33120'],
            ['nombre' => 'Reparación y mantenimiento de equipo electrónico y óptico', 'codigo_mh' => '33130'],
            ['nombre' => 'Reparación y mantenimiento de equipo eléctrico', 'codigo_mh' => '33140'],
            ['nombre' => 'Reparación y mantenimiento de equipo de transporte, excepto vehículos automotores', 'codigo_mh' => '33150'],
            ['nombre' => 'Reparación y mantenimiento de equipos n.c.p.', 'codigo_mh' => '33190'],
            ['nombre' => 'Instalación de maquinaria y equipo industrial', 'codigo_mh' => '33200'],
            ['nombre' => 'Generación de energía eléctrica', 'codigo_mh' => '35101'],
            ['nombre' => 'Transmisión de energía eléctrica', 'codigo_mh' => '35102'],
            ['nombre' => 'Distribución de energía eléctrica', 'codigo_mh' => '35103'],
            ['nombre' => 'Fabricación de gas, distribución de combustibles gaseosos por tuberías', 'codigo_mh' => '35200'],
            ['nombre' => 'Suministro de vapor y agua caliente', 'codigo_mh' => '35300'],
            ['nombre' => 'Captación, tratamiento y suministro de agua', 'codigo_mh' => '36000'],
            ['nombre' => 'Evacuación de aguas residuales (alcantarillado)', 'codigo_mh' => '37000'],
            ['nombre' => 'Recolección y transporte de desechos sólidos proveniente de hogares y sector urbano', 'codigo_mh' => '38110'],
            ['nombre' => 'Recolección de desechos peligrosos', 'codigo_mh' => '38120'],
            ['nombre' => 'Tratamiento y eliminación de desechos inicuos', 'codigo_mh' => '38210'],
            ['nombre' => 'Tratamiento y eliminación de desechos peligrosos', 'codigo_mh' => '38220'],
            ['nombre' => 'Reciclaje de desperdicios y desechos textiles', 'codigo_mh' => '38301'],
            ['nombre' => 'Reciclaje de desperdicios y desechos de plástico y caucho', 'codigo_mh' => '38302'],
            ['nombre' => 'Reciclaje de desperdicios y desechos de vidrio', 'codigo_mh' => '38303'],
            ['nombre' => 'Reciclaje de desperdicios y desechos de papel y cartón', 'codigo_mh' => '38304'],
            ['nombre' => 'Reciclaje de desperdicios y desechos metálicos', 'codigo_mh' => '38305'],
            ['nombre' => 'Reciclaje de desperdicios y desechos no metálicos n.c.p.', 'codigo_mh' => '38309'],
            ['nombre' => 'Actividades de Saneamiento y otros Servicios de Gestión de Desechos', 'codigo_mh' => '39000'],
            ['nombre' => 'Construcción de edificios residenciales', 'codigo_mh' => '41001'],
            ['nombre' => 'Construcción de edificios no residenciales', 'codigo_mh' => '41002'],
            ['nombre' => 'Construcción de carreteras, calles y caminos', 'codigo_mh' => '42100'],
            ['nombre' => 'Construcción de proyectos de servicio público', 'codigo_mh' => '42200'],
            ['nombre' => 'Construcción de obras de ingeniería civil n.c.p.', 'codigo_mh' => '42900'],
            ['nombre' => 'Demolición', 'codigo_mh' => '43110'],
            ['nombre' => 'Preparación de terreno', 'codigo_mh' => '43120'],
            ['nombre' => 'Instalaciones eléctricas', 'codigo_mh' => '43210'],
            ['nombre' => 'Instalación de fontanería, calefacción y aire acondicionado', 'codigo_mh' => '43220'],
            ['nombre' => 'Otras instalaciones para obras de construcción', 'codigo_mh' => '43290'],
            ['nombre' => 'Terminación y acabado de edificios', 'codigo_mh' => '43300'],
            ['nombre' => 'Otras actividades especializadas de construcción', 'codigo_mh' => '43900'],
            ['nombre' => 'Fabricación de techos y materiales diversos', 'codigo_mh' => '43901'],
            ['nombre' => 'Venta de vehículos automotores', 'codigo_mh' => '45100'],
            ['nombre' => 'Reparación mecánica de vehículos automotores', 'codigo_mh' => '45201'],
            ['nombre' => 'Reparaciones eléctricas del automotor y recarga de baterías', 'codigo_mh' => '45202'],
            ['nombre' => 'Enderezado y pintura de vehículos automotores', 'codigo_mh' => '45203'],
            ['nombre' => 'Reparaciones de radiadores, escapes y silenciadores', 'codigo_mh' => '45204'],
            ['nombre' => 'Reparación y reconstrucción de vías, stop y otros artículos de fibra de vidrio', 'codigo_mh' => '45205'],
            ['nombre' => 'Reparación de llantas de vehículos automotores', 'codigo_mh' => '45206'],
            ['nombre' => 'Polarizado de vehículos (mediante la adhesión de papel especial a los vidrios)', 'codigo_mh' => '45207'],
            ['nombre' => 'Lavado y pasteado de vehículos (carwash)', 'codigo_mh' => '45208'],
            ['nombre' => 'Reparaciones de vehículos n.c.p.', 'codigo_mh' => '45209'],
            ['nombre' => 'Remolque de vehículos automotores', 'codigo_mh' => '45211'],
            ['nombre' => 'Venta de partes, piezas y accesorios nuevos para vehículos automotores', 'codigo_mh' => '45301'],
            ['nombre' => 'Venta de partes, piezas y accesorios usados para vehículos automotores', 'codigo_mh' => '45302'],
            ['nombre' => 'Venta de motocicletas', 'codigo_mh' => '45401'],
            ['nombre' => 'Venta de repuestos, piezas y accesorios de motocicletas', 'codigo_mh' => '45402'],
            ['nombre' => 'Mantenimiento y reparación de motocicletas', 'codigo_mh' => '45403'],
            ['nombre' => 'Venta al por mayor a cambio de retribución o por contrata', 'codigo_mh' => '46100'],
            ['nombre' => 'Venta al por mayor de materias primas agrícolas', 'codigo_mh' => '46201'],
            ['nombre' => 'Venta al por mayor de productos de la silvicultura', 'codigo_mh' => '46202'],
            ['nombre' => 'Venta al por mayor de productos pecuarios y de granja', 'codigo_mh' => '46203'],
            ['nombre' => 'Venta de productos para uso agropecuario', 'codigo_mh' => '46211'],
            ['nombre' => 'Venta al por mayor de granos básicos (cereales, leguminosas)', 'codigo_mh' => '46291'],
            ['nombre' => 'Venta al por mayor de semillas mejoradas para cultivo', 'codigo_mh' => '46292'],
            ['nombre' => 'Venta al por mayor de café oro y uva', 'codigo_mh' => '46293'],
            ['nombre' => 'Venta al por mayor de caña de azúcar', 'codigo_mh' => '46294'],
            ['nombre' => 'Venta al por mayor de flores, plantas y otros productos naturales', 'codigo_mh' => '46295'],
            ['nombre' => 'Venta al por mayor de productos agrícolas', 'codigo_mh' => '46296'],
            ['nombre' => 'Venta al por mayor de ganado bovino (vivo)', 'codigo_mh' => '46297'],
            ['nombre' => 'Venta al por mayor de animales porcinos, ovinos, caprino, canículas, apícolas, avícolas vivos', 'codigo_mh' => '46298'],
            ['nombre' => 'Venta de otras especies vivas del reino animal', 'codigo_mh' => '46299'],
            ['nombre' => 'Venta al por mayor de alimentos', 'codigo_mh' => '46301'],
            ['nombre' => 'Venta al por mayor de bebidas', 'codigo_mh' => '46302'],
            ['nombre' => 'Venta al por mayor de tabaco', 'codigo_mh' => '46303'],
            ['nombre' => 'Venta al por mayor de frutas, hortalizas (verduras), legumbres y tubérculos', 'codigo_mh' => '46371'],
            ['nombre' => 'Venta al por mayor de pollos, gallinas destazadas, pavos y otras aves', 'codigo_mh' => '46372'],
            ['nombre' => 'Venta al por mayor de carne bovina y porcina, productos de carne y embutidos', 'codigo_mh' => '46373'],
            ['nombre' => 'Venta al por mayor de huevos', 'codigo_mh' => '46374'],
            ['nombre' => 'Venta al por mayor de productos lácteos', 'codigo_mh' => '46375'],
            ['nombre' => 'Venta al por mayor de productos farináceos de panadería (pan dulce, cakes, repostería, etc.)', 'codigo_mh' => '46376'],
            ['nombre' => 'Venta al por mayor de pastas alimenticias, aceites y grasas comestibles vegetal y animal', 'codigo_mh' => '46377'],
            ['nombre' => 'Venta al por mayor de sal comestible', 'codigo_mh' => '46378'],
            ['nombre' => 'Venta al por mayor de azúcar', 'codigo_mh' => '46379'],
            ['nombre' => 'Venta al por mayor de abarrotes (vinos, licores, productos alimenticios envasados, etc.)', 'codigo_mh' => '46391'],
            ['nombre' => 'Venta al por mayor de aguas gaseosas', 'codigo_mh' => '46392'],
            ['nombre' => 'Venta al por mayor de agua purificada', 'codigo_mh' => '46393'],
            ['nombre' => 'Venta al por mayor de refrescos y otras bebidas, líquidas o en polvo', 'codigo_mh' => '46394'],
            ['nombre' => 'Venta al por mayor de cerveza y licores', 'codigo_mh' => '46395'],
            ['nombre' => 'Venta al por mayor de hielo', 'codigo_mh' => '46396'],
            ['nombre' => 'Venta al por mayor de hilados, tejidos y productos textiles de mercería', 'codigo_mh' => '46411'],
            ['nombre' => 'Venta al por mayor de artículos textiles excepto confecciones para el hogar', 'codigo_mh' => '46412'],
            ['nombre' => 'Venta al por mayor de confecciones textiles para el hogar', 'codigo_mh' => '46413'],
            ['nombre' => 'Venta al por mayor de prendas de vestir y accesorios de vestir', 'codigo_mh' => '46414'],
            ['nombre' => 'Venta al por mayor de ropa usada', 'codigo_mh' => '46415'],
            ['nombre' => 'Venta al por mayor de calzado', 'codigo_mh' => '46416'],
            ['nombre' => 'Venta al por mayor de artículos de marroquinería y talabartería', 'codigo_mh' => '46417'],
            ['nombre' => 'Venta al por mayor de artículos de peletería', 'codigo_mh' => '46418'],
            ['nombre' => 'Venta al por mayor de otros artículos textiles n.c.p.', 'codigo_mh' => '46419'],
            ['nombre' => 'Venta al por mayor de instrumentos musicales', 'codigo_mh' => '46471'],
            ['nombre' => 'Venta al por mayor de colchones, almohadas, cojines, etc.', 'codigo_mh' => '46472'],
            ['nombre' => 'Venta al por mayor de artículos de aluminio para el hogar y para otros usos', 'codigo_mh' => '46473'],
            ['nombre' => 'Venta al por mayor de depósitos y otros artículos plásticos para el hogar y otros usos, incluyendo los desechables de durapax y no desechables', 'codigo_mh' => '46474'],
            ['nombre' => 'Venta al por mayor de cámaras fotográficas, accesorios y materiales', 'codigo_mh' => '46475'],
            ['nombre' => 'Venta al por mayor de medicamentos, artículos y otros productos de uso veterinario', 'codigo_mh' => '46482'],
            ['nombre' => 'Venta al por mayor de productos y artículos de belleza y de uso personal', 'codigo_mh' => '46483'],
            ['nombre' => 'Venta de productos farmacéuticos y medicinales', 'codigo_mh' => '46484'],
            ['nombre' => 'Venta al por mayor de productos medicinales, cosméticos, perfumería y productos de limpieza', 'codigo_mh' => '46491'],
            ['nombre' => 'Venta al por mayor de relojes y artículos de joyería', 'codigo_mh' => '46492'],
            ['nombre' => 'Venta al por mayor de electrodomésticos y artículos del hogar excepto bazar; artículos de iluminación', 'codigo_mh' => '46493'],
            ['nombre' => 'Venta al por mayor de artículos de bazar y similares', 'codigo_mh' => '46494'],
            ['nombre' => 'Venta al por mayor de artículos de óptica', 'codigo_mh' => '46495'],
            ['nombre' => 'Venta al por mayor de revistas, periódicos, libros, artículos de librería y artículos de papel y cartón en general', 'codigo_mh' => '46496'],
            ['nombre' => 'Venta de artículos deportivos, juguetes y rodados', 'codigo_mh' => '46497'],
            ['nombre' => 'Venta al por mayor de productos usados para el hogar o el uso personal', 'codigo_mh' => '46498'],
            ['nombre' => 'Venta al por mayor de enseres domésticos y de uso personal n.c.p.', 'codigo_mh' => '46499'],
            ['nombre' => 'Venta al por mayor de bicicletas, partes, accesorios y otros', 'codigo_mh' => '46500'],
            ['nombre' => 'Venta al por mayor de computadoras, equipo periférico y programas informáticos', 'codigo_mh' => '46510'],
            ['nombre' => 'Venta al por mayor de equipos de comunicación', 'codigo_mh' => '46520'],
            ['nombre' => 'Venta al por mayor de maquinaria y equipo agropecuario, accesorios, partes y suministros', 'codigo_mh' => '46530'],
            ['nombre' => 'Venta de equipos e instrumentos de uso profesional y científico y aparatos de medida y control', 'codigo_mh' => '46590'],
            ['nombre' => 'Venta al por mayor de maquinaria equipo, accesorios y materiales para la industria de la madera y sus productos', 'codigo_mh' => '46591'],
            ['nombre' => 'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria gráfica y del papel, cartón y productos de papel y cartón', 'codigo_mh' => '46592'],
            ['nombre' => 'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria de productos químicos, plástico y caucho', 'codigo_mh' => '46593'],
            ['nombre' => 'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria metálica y de sus productos', 'codigo_mh' => '46594'],
            ['nombre' => 'Venta al por mayor de equipamiento para uso médico, odontológico, veterinario y servicios conexos', 'codigo_mh' => '46595'],
            ['nombre' => 'Venta al por mayor de maquinaria, equipo, accesorios y partes para la industria de la alimentación', 'codigo_mh' => '46596'],
            ['nombre' => 'Venta al por mayor de maquinaria, equipo, accesorios y partes para la industria textil, confecciones y cuero', 'codigo_mh' => '46597'],
            ['nombre' => 'Venta al por mayor de maquinaria, equipo, accesorios y partes para la construcción y explotación de minas y canteras', 'codigo_mh' => '46598'],
            ['nombre' => 'Venta al por mayor de otro tipo de maquinaria y equipo con sus accesorios y partes', 'codigo_mh' => '46599'],
            ['nombre' => 'Venta al por mayor de otros combustibles sólidos, líquidos, gaseosos y de productos conexos', 'codigo_mh' => '46610'],
            ['nombre' => 'Venta al por mayor de combustibles para automotores, aviones, barcos, maquinaria y otros', 'codigo_mh' => '46612'],
            ['nombre' => 'Venta al por mayor de lubricantes, grasas y otros aceites para automotores, maquinaria industrial, etc.', 'codigo_mh' => '46613'],
            ['nombre' => 'Venta al por mayor de gas propano', 'codigo_mh' => '46614'],
            ['nombre' => 'Venta al por mayor de leña y carbón', 'codigo_mh' => '46615'],
            ['nombre' => 'Venta al por mayor de metales y minerales metalíferos', 'codigo_mh' => '46620'],
            ['nombre' => 'Venta al por mayor de puertas, ventanas, vitrinas y similares', 'codigo_mh' => '46631'],
            ['nombre' => 'Venta al por mayor de artículos de ferretería y pinturerías', 'codigo_mh' => '46632'],
            ['nombre' => 'Vidrierías', 'codigo_mh' => '46633'],
            ['nombre' => 'Venta al por mayor de maderas', 'codigo_mh' => '46634'],
            ['nombre' => 'Venta al por mayor de materiales para la construcción n.c.p.', 'codigo_mh' => '46639'],
            ['nombre' => 'Venta al por mayor de sal industrial sin yodar', 'codigo_mh' => '46691'],
            ['nombre' => 'Venta al por mayor de productos intermedios y desechos de origen textil', 'codigo_mh' => '46692'],
            ['nombre' => 'Venta al por mayor de productos intermedios y desechos de origen metálico', 'codigo_mh' => '46693'],
            ['nombre' => 'Venta al por mayor de productos intermedios y desechos de papel y cartón', 'codigo_mh' => '46694'],
            ['nombre' => 'Venta al por mayor fertilizantes, abonos, agroquímicos y productos similares', 'codigo_mh' => '46695'],
            ['nombre' => 'Venta al por mayor de productos intermedios y desechos de origen plástico', 'codigo_mh' => '46696'],
            ['nombre' => 'Venta al por mayor de tintas para imprenta, productos curtientes y materias y productos colorantes', 'codigo_mh' => '46697'],
            ['nombre' => 'Venta de productos intermedios y desechos de origen químico y de caucho', 'codigo_mh' => '46698'],
            ['nombre' => 'Venta al por mayor de productos intermedios y desechos ncp', 'codigo_mh' => '46699'],
            ['nombre' => 'Venta de algodón en oro', 'codigo_mh' => '46701'],
            ['nombre' => 'Venta al por mayor de otros productos', 'codigo_mh' => '46900'],
            ['nombre' => 'Venta al por mayor de cohetes y otros productos pirotécnicos', 'codigo_mh' => '46901'],
            ['nombre' => 'Venta al por mayor de artículos diversos para consumo humano', 'codigo_mh' => '46902'],
            ['nombre' => 'Venta al por mayor de armas de fuego, municiones y accesorios', 'codigo_mh' => '46903'],
            ['nombre' => 'Venta al por mayor de toldos y tiendas de campaña de cualquier material', 'codigo_mh' => '46904'],
            ['nombre' => 'Venta al por mayor de exhibidores publicitarios y rótulos', 'codigo_mh' => '46905'],
            ['nombre' => 'Venta al por mayor de artículos promocionales diversos', 'codigo_mh' => '46906'],
            ['nombre' => 'Venta en supermercados', 'codigo_mh' => '47111'],
            ['nombre' => 'Venta en tiendas de artículos de primera necesidad', 'codigo_mh' => '47112'],
            ['nombre' => 'Venta al por menor de otros productos en comercios no especializados', 'codigo_mh' => '47190'],
            ['nombre' => 'Venta de establecimientos no especializados con surtido compuesto principalmente de alimentos, bebidas y tabaco', 'codigo_mh' => '47199'],
            ['nombre' => 'Venta al por menor de frutas y hortalizas', 'codigo_mh' => '47211'],
            ['nombre' => 'Venta al por menor de carnes, embutidos y productos de granja', 'codigo_mh' => '47212'],
            ['nombre' => 'Venta al por menor de pescado y mariscos', 'codigo_mh' => '47213'],
            ['nombre' => 'Venta al por menor de productos lácteos', 'codigo_mh' => '47214'],
            ['nombre' => 'Venta al por menor de productos de panadería, repostería y galletas', 'codigo_mh' => '47215'],
            ['nombre' => 'Venta al por menor de huevos', 'codigo_mh' => '47216'],
            ['nombre' => 'Venta al por menor de carnes y productos cárnicos', 'codigo_mh' => '47217'],
            ['nombre' => 'Venta al por menor de granos básicos y otros', 'codigo_mh' => '47218'],
            ['nombre' => 'Venta al por menor de alimentos n.c.p.', 'codigo_mh' => '47219'],
            ['nombre' => 'Venta al por menor de hielo', 'codigo_mh' => '47221'],
            ['nombre' => 'Venta de bebidas no alcohólicas, para su consumo fuera del establecimiento', 'codigo_mh' => '47223'],
            ['nombre' => 'Venta de bebidas alcohólicas, para su consumo fuera del establecimiento', 'codigo_mh' => '47224'],
            ['nombre' => 'Venta de bebidas alcohólicas para su consumo dentro del establecimiento', 'codigo_mh' => '47225'],
            ['nombre' => 'Venta al por menor de tabaco', 'codigo_mh' => '47230'],
            ['nombre' => 'Venta de combustibles, lubricantes y otros (gasolineras)', 'codigo_mh' => '47300'],
            ['nombre' => 'Venta al por menor de computadoras y equipo periférico', 'codigo_mh' => '47411'],
            ['nombre' => 'Venta de equipo y accesorios de telecomunicación', 'codigo_mh' => '47412'],
            ['nombre' => 'Venta al por menor de equipo de audio y video', 'codigo_mh' => '47420'],
            ['nombre' => 'Venta al por menor de hilados, tejidos y productos textiles de mercería; confecciones para el hogar y textiles n.c.p.', 'codigo_mh' => '47510'],
            ['nombre' => 'Venta al por menor de productos de madera', 'codigo_mh' => '47521'],
            ['nombre' => 'Venta al por menor de artículos de ferretería', 'codigo_mh' => '47522'],
            ['nombre' => 'Venta al por menor de productos de pinturerías', 'codigo_mh' => '47523'],
            ['nombre' => 'Venta al por menor en vidrierías', 'codigo_mh' => '47524'],
            ['nombre' => 'Venta al por menor de materiales de construcción y artículos conexos', 'codigo_mh' => '47529'],
            ['nombre' => 'Venta al por menor de tapices, alfombras y revestimientos de paredes y pisos en comercios especializados', 'codigo_mh' => '47530'],
            ['nombre' => 'Venta al por menor de muebles', 'codigo_mh' => '47591'],
            ['nombre' => 'Venta al por menor de artículos de bazar', 'codigo_mh' => '47592'],
            ['nombre' => 'Venta al por menor de aparatos electrodomésticos, repuestos y accesorios', 'codigo_mh' => '47593'],
            ['nombre' => 'Venta al por menor de artículos eléctricos y de iluminación', 'codigo_mh' => '47594'],
            ['nombre' => 'Venta al por menor de instrumentos musicales', 'codigo_mh' => '47598'],
            ['nombre' => 'Venta al por menor de libros, periódicos y artículos de papelería en comercios especializados', 'codigo_mh' => '47610'],
            ['nombre' => 'Venta al por menor de discos láser, cassettes, cintas de video y otros', 'codigo_mh' => '47620'],
            ['nombre' => 'Venta al por menor de productos y equipos de deporte', 'codigo_mh' => '47630'],
            ['nombre' => 'Venta al por menor de bicicletas, accesorios y repuestos', 'codigo_mh' => '47631'],
            ['nombre' => 'Venta al por menor de juegos y juguetes en comercios especializados', 'codigo_mh' => '47640'],
            ['nombre' => 'Venta al por menor de prendas de vestir y accesorios de vestir', 'codigo_mh' => '47711'],
            ['nombre' => 'Venta al por menor de calzado', 'codigo_mh' => '47712'],
            ['nombre' => 'Venta al por menor de artículos de peletería, marroquinería y talabartería', 'codigo_mh' => '47713'],
            ['nombre' => 'Venta al por menor de medicamentos farmacéuticos y otros materiales y artículos de uso médico, odontológico y veterinario', 'codigo_mh' => '47721'],
            ['nombre' => 'Venta al por menor de productos cosméticos y de tocador', 'codigo_mh' => '47722'],
            ['nombre' => 'Venta al por menor de productos de joyería, bisutería, óptica, relojería', 'codigo_mh' => '47731'],
            ['nombre' => 'Venta al por menor de plantas, semillas, animales y artículos conexos', 'codigo_mh' => '47732'],
            ['nombre' => 'Venta al por menor de combustibles de uso doméstico (gas propano y gas licuado)', 'codigo_mh' => '47733'],
            ['nombre' => 'Venta al por menor de artesanías, artículos cerámicos y recuerdos en general', 'codigo_mh' => '47734'],
            ['nombre' => 'Venta al por menor de ataúdes, lápidas y cruces, trofeos, artículos religiosos en general', 'codigo_mh' => '47735'],
            ['nombre' => 'Venta al por menor de armas de fuego, municiones y accesorios', 'codigo_mh' => '47736'],
            ['nombre' => 'Venta al por menor de artículos de cohetería y pirotécnicos', 'codigo_mh' => '47737'],
            ['nombre' => 'Venta al por menor de artículos desechables de uso personal y doméstico (servilletas, papel higiénico, pañales, toallas sanitarias, etc.)', 'codigo_mh' => '47738'],
            ['nombre' => 'Venta al por menor de otros productos n.c.p.', 'codigo_mh' => '47739'],
            ['nombre' => 'Venta al por menor de artículos usados', 'codigo_mh' => '47741'],
            ['nombre' => 'Venta al por menor de textiles y confecciones usados', 'codigo_mh' => '47742'],
            ['nombre' => 'Venta al por menor de libros, revistas, papel y cartón usados', 'codigo_mh' => '47743'],
            ['nombre' => 'Venta al por menor de productos usados n.c.p.', 'codigo_mh' => '47749'],
            ['nombre' => 'Venta al por menor de frutas, verduras y hortalizas', 'codigo_mh' => '47811'],
            ['nombre' => 'Venta al por menor de productos lácteos', 'codigo_mh' => '47814'],
            ['nombre' => 'Venta al por menor de productos de panadería, galletas y similares', 'codigo_mh' => '47815'],
            ['nombre' => 'Venta al por menor de bebidas', 'codigo_mh' => '47816'],
            ['nombre' => 'Venta al por menor en tiendas de mercado y puestos', 'codigo_mh' => '47818'],
            ['nombre' => 'Venta al por menor de hilados, tejidos y productos textiles de mercería en puestos de mercados y ferias', 'codigo_mh' => '47821'],
            ['nombre' => 'Venta al por menor de artículos textiles excepto confecciones para el hogar en puestos de mercados y ferias', 'codigo_mh' => '47822'],
            ['nombre' => 'Venta al por menor de confecciones textiles para el hogar en puestos de mercados y ferias', 'codigo_mh' => '47823'],
            ['nombre' => 'Venta al por menor de prendas de vestir, accesorios de vestir y similares en puestos de mercados y ferias', 'codigo_mh' => '47824'],
            ['nombre' => 'Venta al por menor de ropa usada', 'codigo_mh' => '47825'],
            ['nombre' => 'Venta al por menor de calzado, artículos de marroquinería y talabartería en puestos de mercados y ferias', 'codigo_mh' => '47826'],
            ['nombre' => 'Venta al por menor de artículos de marroquinería y talabartería en puestos de mercados y ferias', 'codigo_mh' => '47827'],
            ['nombre' => 'Venta al por menor de artículos textiles ncp en puestos de mercados y ferias', 'codigo_mh' => '47829'],
            ['nombre' => 'Venta al por menor de animales, flores y productos conexos en puestos de feria y mercados', 'codigo_mh' => '47891'],
            ['nombre' => 'Venta al por menor de productos medicinales, cosméticos, de tocador y de limpieza en puestos de ferias y mercados', 'codigo_mh' => '47892'],
            ['nombre' => 'Venta al por menor de artículos de bazar en puestos de ferias y mercados', 'codigo_mh' => '47893'],
            ['nombre' => 'Venta al por menor de artículos de papel, envases, libros, revistas y conexos en puestos de feria y mercados', 'codigo_mh' => '47894'],
            ['nombre' => 'Venta al por menor de materiales de construcción, electrodomésticos, accesorios para autos y similares en puestos de feria y mercados', 'codigo_mh' => '47895'],
            ['nombre' => 'Venta al por menor de equipos accesorios para las comunicaciones en puestos de feria y mercados', 'codigo_mh' => '47896'],
            ['nombre' => 'Venta al por menor en puestos de ferias y mercados n.c.p.', 'codigo_mh' => '47899'],
            ['nombre' => 'Venta al por menor por correo o Internet', 'codigo_mh' => '47910'],
            ['nombre' => 'Otros tipos de venta al por menor no realizada, en almacenes, puestos de venta o mercado', 'codigo_mh' => '47990'],
            ['nombre' => 'Transporte interurbano de pasajeros por ferrocarril', 'codigo_mh' => '49110'],
            ['nombre' => 'Transporte de carga por ferrocarril', 'codigo_mh' => '49120'],
            ['nombre' => 'Transporte de pasajeros urbanos e interurbano mediante buses', 'codigo_mh' => '49211'],
            ['nombre' => 'Transporte de pasajeros interdepartamental mediante microbuses', 'codigo_mh' => '49212'],
            ['nombre' => 'Transporte de pasajeros urbanos e interurbano mediante microbuses', 'codigo_mh' => '49213'],
            ['nombre' => 'Transporte de pasajeros interdepartamental mediante buses', 'codigo_mh' => '49214'],
            ['nombre' => 'Transporte internacional de pasajeros', 'codigo_mh' => '49221'],
            ['nombre' => 'Transporte de pasajeros mediante taxis y autos con chofer', 'codigo_mh' => '49222'],
            ['nombre' => 'Transporte escolar', 'codigo_mh' => '49223'],
            ['nombre' => 'Transporte de pasajeros para excursiones', 'codigo_mh' => '49225'],
            ['nombre' => 'Servicios de transporte de personal', 'codigo_mh' => '49226'],
            ['nombre' => 'Transporte de pasajeros por vía terrestre ncp', 'codigo_mh' => '49229'],
            ['nombre' => 'Transporte de carga urbano', 'codigo_mh' => '49231'],
            ['nombre' => 'Transporte nacional de carga', 'codigo_mh' => '49232'],
            ['nombre' => 'Transporte de carga internacional', 'codigo_mh' => '49233'],
            ['nombre' => 'Servicios de mudanza', 'codigo_mh' => '49234'],
            ['nombre' => 'Alquiler de vehículos de carga con conductor', 'codigo_mh' => '49235'],
            ['nombre' => 'Transporte por oleoducto o gasoducto', 'codigo_mh' => '49300'],
            ['nombre' => 'Transporte de pasajeros marítimo y de cabotaje', 'codigo_mh' => '50110'],
            ['nombre' => 'Transporte de carga marítimo y de cabotaje', 'codigo_mh' => '50120'],
            ['nombre' => 'Transporte de pasajeros por vías de navegación interiores', 'codigo_mh' => '50211'],
            ['nombre' => 'Alquiler de equipo de transporte de pasajeros por vías de navegación interior con conductor', 'codigo_mh' => '50212'],
            ['nombre' => 'Transporte de carga por vías de navegación interiores', 'codigo_mh' => '50220'],
            ['nombre' => 'Transporte aéreo de pasajeros', 'codigo_mh' => '51100'],
            ['nombre' => 'Transporte de carga por vía aérea', 'codigo_mh' => '51201'],
            ['nombre' => 'Alquiler de equipo de aerotransporte con operadores para el propósito de transportar carga', 'codigo_mh' => '51202'],
            ['nombre' => 'Alquiler de instalaciones de almacenamiento en zonas francas', 'codigo_mh' => '52101'],
            ['nombre' => 'Alquiler de silos para conservación y almacenamiento de granos', 'codigo_mh' => '52102'],
            ['nombre' => 'Alquiler de instalaciones con refrigeración para almacenamiento y conservación de alimentos y otros productos', 'codigo_mh' => '52103'],
            ['nombre' => 'Alquiler de bodegas para almacenamiento y depósito n.c.p.', 'codigo_mh' => '52109'],
            ['nombre' => 'Servicio de garaje y estacionamiento', 'codigo_mh' => '52211'],
            ['nombre' => 'Servicios de terminales para el transporte por vía terrestre', 'codigo_mh' => '52212'],
            ['nombre' => 'Servicios para el transporte por vía terrestre n.c.p.', 'codigo_mh' => '52219'],
            ['nombre' => 'Servicios para el transporte acuático', 'codigo_mh' => '52220'],
            ['nombre' => 'Servicios para el transporte aéreo', 'codigo_mh' => '52230'],
            ['nombre' => 'Manipulación de carga', 'codigo_mh' => '52240'],
            ['nombre' => 'Servicios para el transporte ncp', 'codigo_mh' => '52290'],
            ['nombre' => 'Agencias de tramitaciones aduanales', 'codigo_mh' => '52291'],
            ['nombre' => 'Servicios de correo nacional', 'codigo_mh' => '53100'],
            ['nombre' => 'Actividades de correo distintas a las actividades postales nacionales', 'codigo_mh' => '53200'],
            ['nombre' => 'Actividades de alojamiento para estancias cortas', 'codigo_mh' => '55101'],
            ['nombre' => 'Hoteles', 'codigo_mh' => '55102'],
            ['nombre' => 'Actividades de campamentos, parques de vehículos de recreo y parques de caravanas', 'codigo_mh' => '55200'],
            ['nombre' => 'Alojamiento n.c.p.', 'codigo_mh' => '55900'],
            ['nombre' => 'Restaurantes', 'codigo_mh' => '56101'],
            ['nombre' => 'Pupusería', 'codigo_mh' => '56106'],
            ['nombre' => 'Actividades varias de restaurantes', 'codigo_mh' => '56107'],
            ['nombre' => 'Comedores', 'codigo_mh' => '56108'],
            ['nombre' => 'Merenderos ambulantes', 'codigo_mh' => '56109'],
            ['nombre' => 'Preparación de comida para eventos especiales', 'codigo_mh' => '56210'],
            ['nombre' => 'Servicios de provisión de comidas por contrato', 'codigo_mh' => '56291'],
            ['nombre' => 'Servicios de concesión de cafetines y chalet en empresas e instituciones', 'codigo_mh' => '56292'],
            ['nombre' => 'Servicios de preparación de comidas ncp', 'codigo_mh' => '56299'],
            ['nombre' => 'Servicio de expendio de bebidas en salones y bares', 'codigo_mh' => '56301'],
            ['nombre' => 'Servicio de expendio de bebidas en puestos callejeros, mercados y ferias', 'codigo_mh' => '56302'],
            ['nombre' => 'Edición de libros, folletos, partituras y otras ediciones distintas a estas', 'codigo_mh' => '58110'],
            ['nombre' => 'Edición de directorios y listas de correos', 'codigo_mh' => '58120'],
            ['nombre' => 'Edición de periódicos, revistas y otras publicaciones periódicas', 'codigo_mh' => '58130'],
            ['nombre' => 'Otras actividades de edición', 'codigo_mh' => '58190'],
            ['nombre' => 'Edición de programas informáticos (software)', 'codigo_mh' => '58200'],
            ['nombre' => 'Actividades de producción cinematográfica', 'codigo_mh' => '59110'],
            ['nombre' => 'Actividades de postproducción de películas, videos y programas de televisión', 'codigo_mh' => '59120'],
            ['nombre' => 'Actividades de distribución de películas cinematográficas, videos y programas de televisión', 'codigo_mh' => '59130'],
            ['nombre' => 'Actividades de exhibición de películas cinematográficas y cintas de vídeo', 'codigo_mh' => '59140'],
            ['nombre' => 'Actividades de edición y grabación de música', 'codigo_mh' => '59200'],
            ['nombre' => 'Servicios de difusión de radio', 'codigo_mh' => '60100'],
            ['nombre' => 'Actividades de programación y difusión de televisión abierta', 'codigo_mh' => '60201'],
            ['nombre' => 'Actividades de suscripción y difusión de televisión por cable y/o suscripción', 'codigo_mh' => '60202'],
            ['nombre' => 'Servicios de televisión, incluye televisión por cable', 'codigo_mh' => '60299'],
            ['nombre' => 'Programación y transmisión de radio y televisión', 'codigo_mh' => '60900'],
            ['nombre' => 'Servicio de telefonía', 'codigo_mh' => '61101'],
            ['nombre' => 'Servicio de Internet', 'codigo_mh' => '61102'],
            ['nombre' => 'Servicio de telefonía fija', 'codigo_mh' => '61103'],
            ['nombre' => 'Servicio de Internet n.c.p.', 'codigo_mh' => '61109'],
            ['nombre' => 'Servicios de telefonía celular', 'codigo_mh' => '61201'],
            ['nombre' => 'Servicios de Internet inalámbrico', 'codigo_mh' => '61202'],
            ['nombre' => 'Servicios de telecomunicaciones inalámbrico n.c.p.', 'codigo_mh' => '61209'],
            ['nombre' => 'Telecomunicaciones satelitales', 'codigo_mh' => '61301'],
            ['nombre' => 'Comunicación vía satélite n.c.p.', 'codigo_mh' => '61309'],
            ['nombre' => 'Actividades de telecomunicación n.c.p.', 'codigo_mh' => '61900'],
            ['nombre' => 'Programación informática', 'codigo_mh' => '62010'],
            ['nombre' => 'Consultorías y gestión de servicios informáticos', 'codigo_mh' => '62020'],
            ['nombre' => 'Otras actividades de tecnología de información y servicios de computadora', 'codigo_mh' => '62090'],
            ['nombre' => 'Procesamiento de datos y actividades relacionadas', 'codigo_mh' => '63110'],
            ['nombre' => 'Portales WEB', 'codigo_mh' => '63120'],
            ['nombre' => 'Servicios de Agencias de Noticias', 'codigo_mh' => '63910'],
            ['nombre' => 'Otros servicios de información n.c.p.', 'codigo_mh' => '63990'],
            ['nombre' => 'Servicios provistos por el Banco Central de El Salvador', 'codigo_mh' => '64110'],
            ['nombre' => 'Bancos', 'codigo_mh' => '64190'],
            ['nombre' => 'Entidades dedicadas al envío de remesas', 'codigo_mh' => '64192'],
            ['nombre' => 'Otras entidades financieras', 'codigo_mh' => '64199'],
            ['nombre' => 'Actividades de sociedades de cartera', 'codigo_mh' => '64200'],
            ['nombre' => 'Fideicomisos, fondos y otras fuentes de financiamiento', 'codigo_mh' => '64300'],
            ['nombre' => 'Arrendamientos financieros', 'codigo_mh' => '64910'],
            ['nombre' => 'Asociaciones cooperativas de ahorro y crédito dedicadas a la intermediación financiera', 'codigo_mh' => '64920'],
            ['nombre' => 'Instituciones emisoras de tarjetas de crédito y otros', 'codigo_mh' => '64921'],
            ['nombre' => 'Tipos de crédito ncp', 'codigo_mh' => '64922'],
            ['nombre' => 'Prestamistas y casas de empeño', 'codigo_mh' => '64928'],
            ['nombre' => 'Actividades de servicios financieros, excepto la financiación de planes de seguros y de pensiones n.c.p.', 'codigo_mh' => '64990'],
            ['nombre' => 'Planes de seguros de vida', 'codigo_mh' => '65110'],
            ['nombre' => 'Planes de seguro excepto de vida', 'codigo_mh' => '65120'],
            ['nombre' => 'Seguros generales de todo tipo', 'codigo_mh' => '65199'],
            ['nombre' => 'Planes de seguro', 'codigo_mh' => '65200'],
            ['nombre' => 'Planes de pensiones', 'codigo_mh' => '65300'],
            ['nombre' => 'Administración de mercados financieros (Bolsa de Valores)', 'codigo_mh' => '66110'],
            ['nombre' => 'Actividades bursátiles (Corredores de Bolsa)', 'codigo_mh' => '66120'],
            ['nombre' => 'Actividades auxiliares de la intermediación financiera ncp', 'codigo_mh' => '66190'],
            ['nombre' => 'Evaluación de riesgos y daños', 'codigo_mh' => '66210'],
            ['nombre' => 'Actividades de agentes y corredores de seguros', 'codigo_mh' => '66220'],
            ['nombre' => 'Otras actividades auxiliares de seguros y fondos de pensiones', 'codigo_mh' => '66290'],
            ['nombre' => 'Actividades de administración de fondos', 'codigo_mh' => '66300'],
            ['nombre' => 'Servicio de alquiler y venta de lotes en cementerios', 'codigo_mh' => '68101'],
            ['nombre' => 'Actividades inmobiliarias realizadas con bienes propios o arrendados n.c.p.', 'codigo_mh' => '68109'],
            ['nombre' => 'Actividades Inmobiliarias Realizadas a Cambio de una Retribución o por Contrata', 'codigo_mh' => '68200'],
            ['nombre' => 'Actividades jurídicas', 'codigo_mh' => '69100'],
            ['nombre' => 'Actividades de contabilidad, teneduría de libros y auditoría; asesoramiento en materia de impuestos', 'codigo_mh' => '69200'],
            ['nombre' => 'Actividades de oficinas centrales de sociedades de cartera', 'codigo_mh' => '70100'],
            ['nombre' => 'Actividades de consultoría en gestión empresarial', 'codigo_mh' => '70200'],
            ['nombre' => 'Servicios de arquitectura y planificación urbana y servicios conexos', 'codigo_mh' => '71101'],
            ['nombre' => 'Servicios de ingeniería', 'codigo_mh' => '71102'],
            ['nombre' => 'Servicios de agrimensura, topografía, cartografía, prospección y geofísica y servicios conexos', 'codigo_mh' => '71103'],
            ['nombre' => 'Ensayos y análisis técnicos', 'codigo_mh' => '71200'],
            ['nombre' => 'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería', 'codigo_mh' => '72100'],
            ['nombre' => 'Investigaciones científicas', 'codigo_mh' => '72199'],
            ['nombre' => 'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades científica y desarrollo', 'codigo_mh' => '72200'],
            ['nombre' => 'Publicidad', 'codigo_mh' => '73100'],
            ['nombre' => 'Investigación de mercados y realización de encuestas de opinión pública', 'codigo_mh' => '73200'],
            ['nombre' => 'Actividades de diseño especializado', 'codigo_mh' => '74100'],
            ['nombre' => 'Actividades de fotografía', 'codigo_mh' => '74200'],
            ['nombre' => 'Servicios profesionales y científicos ncp', 'codigo_mh' => '74900'],
            ['nombre' => 'Actividades veterinarias', 'codigo_mh' => '75000'],
            ['nombre' => 'Alquiler de equipo de transporte terrestre', 'codigo_mh' => '77101'],
            ['nombre' => 'Alquiler de equipo de transporte acuático', 'codigo_mh' => '77102'],
            ['nombre' => 'Alquiler de equipo de transporte por vía aérea', 'codigo_mh' => '77103'],
            ['nombre' => 'Alquiler y arrendamiento de equipo de recreo y deportivo', 'codigo_mh' => '77210'],
            ['nombre' => 'Alquiler de cintas de video y discos', 'codigo_mh' => '77220'],
            ['nombre' => 'Alquiler de otros efectos personales y enseres domésticos', 'codigo_mh' => '77290'],
            ['nombre' => 'Alquiler de maquinaria y equipo', 'codigo_mh' => '77300'],
            ['nombre' => 'Arrendamiento de productos de propiedad intelectual', 'codigo_mh' => '77400'],
            ['nombre' => 'Obtención y dotación de personal', 'codigo_mh' => '78100'],
            ['nombre' => 'Actividades de las agencias de trabajo temporal', 'codigo_mh' => '78200'],
            ['nombre' => 'Dotación de recursos humanos y gestión; gestión de las funciones de recursos humanos', 'codigo_mh' => '78300'],
            ['nombre' => 'Actividades de agencias de viajes y organizadores de viajes; actividades de asistencia a turistas', 'codigo_mh' => '79110'],
            ['nombre' => 'Actividades de los operadores turísticos', 'codigo_mh' => '79120'],
            ['nombre' => 'Otros servicios de reservas y actividades relacionadas', 'codigo_mh' => '79900'],
            ['nombre' => 'Servicios de seguridad privados', 'codigo_mh' => '80100'],
            ['nombre' => 'Actividades de servicios de sistemas de seguridad', 'codigo_mh' => '80201'],
            ['nombre' => 'Actividades para la prestación de sistemas de seguridad', 'codigo_mh' => '80202'],
            ['nombre' => 'Actividades de investigación', 'codigo_mh' => '80300'],
            ['nombre' => 'Actividades combinadas de mantenimiento de edificios e instalaciones', 'codigo_mh' => '81100'],
            ['nombre' => 'Limpieza general de edificios', 'codigo_mh' => '81210'],
            ['nombre' => 'Otras actividades combinadas de mantenimiento de edificios e instalaciones ncp', 'codigo_mh' => '81290'],
            ['nombre' => 'Servicio de jardinería', 'codigo_mh' => '81300'],
            ['nombre' => 'Servicios administrativos de oficinas', 'codigo_mh' => '82110'],
            ['nombre' => 'Servicio de fotocopiado y similares, excepto en imprentas', 'codigo_mh' => '82190'],
            ['nombre' => 'Actividades de las centrales de llamadas (call center)', 'codigo_mh' => '82200'],
            ['nombre' => 'Organización de convenciones y ferias de negocios', 'codigo_mh' => '82300'],
            ['nombre' => 'Actividades de agencias de cobro y oficinas de crédito', 'codigo_mh' => '82910'],
            ['nombre' => 'Servicios de envase y empaque de productos alimenticios', 'codigo_mh' => '82921'],
            ['nombre' => 'Servicios de envase y empaque de productos medicinales', 'codigo_mh' => '82922'],
            ['nombre' => 'Servicio de envase y empaque ncp', 'codigo_mh' => '82929'],
            ['nombre' => 'Actividades de apoyo empresariales ncp', 'codigo_mh' => '82990'],
            ['nombre' => 'Actividades de la Administración Pública en general', 'codigo_mh' => '84110'],
            ['nombre' => 'Alcaldías municipales', 'codigo_mh' => '84111'],
            ['nombre' => 'Regulación de las actividades de prestación de servicios sanitarios, educativos, culturales y otros servicios sociales, excepto seguridad social', 'codigo_mh' => '84120'],
            ['nombre' => 'Regulación y facilitación de la actividad económica', 'codigo_mh' => '84130'],
            ['nombre' => 'Actividades de administración y funcionamiento del Ministerio de Relaciones Exteriores', 'codigo_mh' => '84210'],
            ['nombre' => 'Actividades de defensa', 'codigo_mh' => '84220'],
            ['nombre' => 'Actividades de mantenimiento del orden público y de seguridad', 'codigo_mh' => '84230'],
            ['nombre' => 'Actividades de planes de seguridad social de afiliación obligatoria', 'codigo_mh' => '84300'],
            ['nombre' => 'Guardería educativa', 'codigo_mh' => '85101'],
            ['nombre' => 'Enseñanza preescolar o parvularia', 'codigo_mh' => '85102'],
            ['nombre' => 'Enseñanza primaria', 'codigo_mh' => '85103'],
            ['nombre' => 'Servicio de educación preescolar y primaria integrada', 'codigo_mh' => '85104'],
            ['nombre' => 'Enseñanza secundaria tercer ciclo (7°, 8° y 9°)', 'codigo_mh' => '85211'],
            ['nombre' => 'Enseñanza secundaria de formación general bachillerato', 'codigo_mh' => '85212'],
            ['nombre' => 'Enseñanza secundaria de formación técnica y profesional', 'codigo_mh' => '85221'],
            ['nombre' => 'Enseñanza secundaria de formación técnica y profesional integrada con enseñanza primaria', 'codigo_mh' => '85222'],
            ['nombre' => 'Enseñanza superior universitaria', 'codigo_mh' => '85301'],
            ['nombre' => 'Enseñanza superior no universitaria', 'codigo_mh' => '85302'],
            ['nombre' => 'Enseñanza superior integrada a educación secundaria y/o primaria', 'codigo_mh' => '85303'],
            ['nombre' => 'Educación deportiva y recreativa', 'codigo_mh' => '85410'],
            ['nombre' => 'Educación cultural', 'codigo_mh' => '85420'],
            ['nombre' => 'Otros tipos de enseñanza n.c.p.', 'codigo_mh' => '85490'],
            ['nombre' => 'Enseñanza formal', 'codigo_mh' => '85499'],
            ['nombre' => 'Servicios de apoyo a la enseñanza', 'codigo_mh' => '85500'],
            ['nombre' => 'Actividades de hospitales', 'codigo_mh' => '86100'],
            ['nombre' => 'Clínicas médicas', 'codigo_mh' => '86201'],
            ['nombre' => 'Servicios de Odontología', 'codigo_mh' => '86202'],
            ['nombre' => 'Servicios médicos', 'codigo_mh' => '86203'],
            ['nombre' => 'Servicios de análisis y estudios de diagnóstico', 'codigo_mh' => '86901'],
            ['nombre' => 'Actividades de atención de la salud humana', 'codigo_mh' => '86902'],
            ['nombre' => 'Otros Servicio relacionados con la salud ncp', 'codigo_mh' => '86909'],
            ['nombre' => 'Residencias de ancianos con atención de enfermería', 'codigo_mh' => '87100'],
            ['nombre' => 'Instituciones dedicadas al tratamiento del retraso mental, problemas de salud mental y el uso indebido de sustancias nocivas', 'codigo_mh' => '87200'],
            ['nombre' => 'Instituciones dedicadas al cuidado de ancianos y discapacitados', 'codigo_mh' => '87300'],
            ['nombre' => 'Actividades de asistencia a niños y jóvenes', 'codigo_mh' => '87900'],
            ['nombre' => 'Otras actividades de atención en instituciones', 'codigo_mh' => '87901'],
            ['nombre' => 'Actividades de asistencia sociales sin alojamiento para ancianos y discapacitados', 'codigo_mh' => '88100'],
            ['nombre' => 'Servicios sociales sin alojamiento ncp', 'codigo_mh' => '88900'],
            ['nombre' => 'Actividades creativas artísticas y de esparcimiento', 'codigo_mh' => '90000'],
            ['nombre' => 'Actividades de bibliotecas y archivos', 'codigo_mh' => '91010'],
            ['nombre' => 'Actividades de museos y preservación de lugares y edificios históricos', 'codigo_mh' => '91020'],
            ['nombre' => 'Actividades de jardines botánicos, zoológicos y de reservas naturales', 'codigo_mh' => '91030'],
            ['nombre' => 'Actividades de juegos y apuestas', 'codigo_mh' => '92000'],
            ['nombre' => 'Gestión de instalaciones deportivas', 'codigo_mh' => '93110'],
            ['nombre' => 'Actividades de clubes deportivos', 'codigo_mh' => '93120'],
            ['nombre' => 'Otras actividades deportivas', 'codigo_mh' => '93190'],
            ['nombre' => 'Actividades de parques de atracciones y parques temáticos', 'codigo_mh' => '93210'],
            ['nombre' => 'Discotecas y salas de baile', 'codigo_mh' => '93291'],
            ['nombre' => 'Centros vacacionales', 'codigo_mh' => '93298'],
            ['nombre' => 'Actividades de esparcimiento ncp', 'codigo_mh' => '93299'],
            ['nombre' => 'Actividades de organizaciones empresariales y de empleadores', 'codigo_mh' => '94110'],
            ['nombre' => 'Actividades de organizaciones profesionales', 'codigo_mh' => '94120'],
            ['nombre' => 'Actividades de sindicatos', 'codigo_mh' => '94200'],
            ['nombre' => 'Actividades de organizaciones religiosas', 'codigo_mh' => '94910'],
            ['nombre' => 'Actividades de organizaciones políticas', 'codigo_mh' => '94920'],
            ['nombre' => 'Actividades de asociaciones n.c.p.', 'codigo_mh' => '94990'],
            ['nombre' => 'Reparación de computadoras y equipo periférico', 'codigo_mh' => '95110'],
            ['nombre' => 'Reparación de equipo de comunicación', 'codigo_mh' => '95120'],
            ['nombre' => 'Reparación de aparatos electrónicos de consumo', 'codigo_mh' => '95210'],
            ['nombre' => 'Reparación de aparatos doméstico y equipo de hogar y jardín', 'codigo_mh' => '95220'],
            ['nombre' => 'Reparación de calzado y artículos de cuero', 'codigo_mh' => '95230'],
            ['nombre' => 'Reparación de muebles y accesorios para el hogar', 'codigo_mh' => '95240'],
            ['nombre' => 'Reparación de Instrumentos musicales', 'codigo_mh' => '95291'],
            ['nombre' => 'Servicios de cerrajería y copiado de llaves', 'codigo_mh' => '95292'],
            ['nombre' => 'Reparación de joyas y relojes', 'codigo_mh' => '95293'],
            ['nombre' => 'Reparación de bicicletas, sillas de ruedas y rodados n.c.p.', 'codigo_mh' => '95294'],
            ['nombre' => 'Reparaciones de enseres personales n.c.p.', 'codigo_mh' => '95299'],
            ['nombre' => 'Lavado y limpieza de prendas de tela y de piel, incluso la limpieza en seco', 'codigo_mh' => '96010'],
            ['nombre' => 'Peluquería y otros tratamientos de belleza', 'codigo_mh' => '96020'],
            ['nombre' => 'Pompas fúnebres y actividades conexas', 'codigo_mh' => '96030'],
            ['nombre' => 'Servicios de sauna y otros servicios para la estética corporal n.c.p.', 'codigo_mh' => '96091'],
            ['nombre' => 'Servicios n.c.p.', 'codigo_mh' => '96092'],
            ['nombre' => 'Actividad de los hogares en calidad de empleadores de personal doméstico', 'codigo_mh' => '97000'],
            ['nombre' => 'Actividades indiferenciadas de producción de bienes de los hogares privados para uso propio', 'codigo_mh' => '98100'],
            ['nombre' => 'Actividades indiferenciadas de producción de servicios de los hogares privados para uso propio', 'codigo_mh' => '98200'],
            ['nombre' => 'Actividades de organizaciones y órganos extraterritoriales', 'codigo_mh' => '99000'],
            ['nombre' => 'Empleados', 'codigo_mh' => '10001'],
            ['nombre' => 'Jubilado', 'codigo_mh' => '10002'],
            ['nombre' => 'Estudiante', 'codigo_mh' => '10003'],
            ['nombre' => 'Desempleado', 'codigo_mh' => '10004'],
            ['nombre' => 'Otros', 'codigo_mh' => '10005'],
        ];


        foreach ($nuevosGiros as $nuevoGiro) {
            Giro::create([
                'nombre' => $nuevoGiro['nombre'],
                'codigo_mh' => $nuevoGiro['codigo_mh'],
                'user_id' => $users->random()->id
            ]);
        }
    }
}
