<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Municipio;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $columns = ['id'];
        $users = User::all($columns);

        $municipios = [
            ['nombre' => 'Apaneca', 'codigo_mh' => '02', 'departamento_id' => '1'],
            ['nombre' => 'Atiquizaya', 'codigo_mh' => '03', 'departamento_id' => '1'],
            ['nombre' => 'Concepción de Ataco', 'codigo_mh' => '04', 'departamento_id' => '1'],
            ['nombre' => 'El refugio', 'codigo_mh' => '05', 'departamento_id' => '1'],
            ['nombre' => 'Guaymango', 'codigo_mh' => '06', 'departamento_id' => '1'],
            ['nombre' => 'Jujutla', 'codigo_mh' => '07', 'departamento_id' => '1'],
            ['nombre' => 'San Francisco Menéndez', 'codigo_mh' => '08', 'departamento_id' => '1'],
            ['nombre' => 'San Lorenzo', 'codigo_mh' => '09', 'departamento_id' => '1'],
            ['nombre' => 'San Pedro Puxtla', 'codigo_mh' => '10', 'departamento_id' => '1'],
            ['nombre' => 'Tacuba', 'codigo_mh' => '11', 'departamento_id' => '1'],
            ['nombre' => 'Turín', 'codigo_mh' => '12', 'departamento_id' => '1'],
            ['nombre' => 'Candelaria de la Frontera', 'codigo_mh' => '01', 'departamento_id' => '2'],
            ['nombre' => 'Coatepeque', 'codigo_mh' => '02', 'departamento_id' => '2'],
            ['nombre' => 'Chalchuapa', 'codigo_mh' => '03', 'departamento_id' => '2'],
            ['nombre' => 'El Congo', 'codigo_mh' => '04', 'departamento_id' => '2'],
            ['nombre' => 'El Porvenir', 'codigo_mh' => '05', 'departamento_id' => '2'],
            ['nombre' => 'Masahuat', 'codigo_mh' => '06', 'departamento_id' => '2'],
            ['nombre' => 'Metapán', 'codigo_mh' => '07', 'departamento_id' => '2'],
            ['nombre' => 'San Antonio Pajonal', 'codigo_mh' => '08', 'departamento_id' => '2'],
            ['nombre' => 'San Sebastián Salitrillo', 'codigo_mh' => '09', 'departamento_id' => '2'],
            ['nombre' => 'Santa Ana', 'codigo_mh' => '10', 'departamento_id' => '2'],
            ['nombre' => 'Santa Rosa Guachi', 'codigo_mh' => '11', 'departamento_id' => '2'],
            ['nombre' => 'Santiago de la Frontera', 'codigo_mh' => '12', 'departamento_id' => '2'],
            ['nombre' => 'Texistepeque', 'codigo_mh' => '13', 'departamento_id' => '2'],
            ['nombre' => 'Acajutla', 'codigo_mh' => '01', 'departamento_id' => '3'],
            ['nombre' => 'Armenia', 'codigo_mh' => '02', 'departamento_id' => '3'],
            ['nombre' => 'Caluco', 'codigo_mh' => '03', 'departamento_id' => '3'],
            ['nombre' => 'Cuisnahuat', 'codigo_mh' => '04', 'departamento_id' => '3'],
            ['nombre' => 'Santa Isabel Ishuatán', 'codigo_mh' => '05', 'departamento_id' => '3'],
            ['nombre' => 'Izalco', 'codigo_mh' => '06', 'departamento_id' => '3'],
            ['nombre' => 'Juayúa', 'codigo_mh' => '07', 'departamento_id' => '3'],
            ['nombre' => 'Nahuizalco', 'codigo_mh' => '08', 'departamento_id' => '3'],
            ['nombre' => 'Nahulingo', 'codigo_mh' => '09', 'departamento_id' => '3'],
            ['nombre' => 'Salcoatitán', 'codigo_mh' => '10', 'departamento_id' => '3'],
            ['nombre' => 'San Antonio del Monte', 'codigo_mh' => '11', 'departamento_id' => '3'],
            ['nombre' => 'San Julían', 'codigo_mh' => '12', 'departamento_id' => '3'],
            ['nombre' => 'Santa Cruz Masahuat', 'codigo_mh' => '13', 'departamento_id' => '3'],
            ['nombre' => 'Santo Domingo Guzmán', 'codigo_mh' => '14', 'departamento_id' => '3'],
            ['nombre' => 'Sonsonate', 'codigo_mh' => '15', 'departamento_id' => '3'],
            ['nombre' => 'Sonzacate', 'codigo_mh' => '16', 'departamento_id' => '3'],
            ['nombre' => 'Agua Caliente', 'codigo_mh' => '01', 'departamento_id' => '4'],
            ['nombre' => 'Arcatao', 'codigo_mh' => '02', 'departamento_id' => '4'],
            ['nombre' => 'Azacualpa', 'codigo_mh' => '03', 'departamento_id' => '4'],
            ['nombre' => 'Comalapa', 'codigo_mh' => '05', 'departamento_id' => '4'],
            ['nombre' => 'Concepción Quezaltepeque', 'codigo_mh' => '06', 'departamento_id' => '4'],
            ['nombre' => 'Chalatenango', 'codigo_mh' => '07', 'departamento_id' => '4'],
            ['nombre' => 'Dulce Nombre de María', 'codigo_mh' => '08', 'departamento_id' => '4'],
            ['nombre' => 'El Carrizal', 'codigo_mh' => '09', 'departamento_id' => '4'],
            ['nombre' => 'El Paraíso', 'codigo_mh' => '10', 'departamento_id' => '4'],
            ['nombre' => 'La Laguna', 'codigo_mh' => '11', 'departamento_id' => '4'],
            ['nombre' => 'La Palma', 'codigo_mh' => '12', 'departamento_id' => '4'],
            ['nombre' => 'La Reina', 'codigo_mh' => '13', 'departamento_id' => '4'],
            ['nombre' => 'Las Vueltas', 'codigo_mh' => '14', 'departamento_id' => '4'],
            ['nombre' => 'Nombre de Jesús', 'codigo_mh' => '15', 'departamento_id' => '4'],
            ['nombre' => 'Nueva Concepción', 'codigo_mh' => '16', 'departamento_id' => '4'],
            ['nombre' => 'Nueva Trinidad', 'codigo_mh' => '17', 'departamento_id' => '4'],
            ['nombre' => 'Ojos de Agua', 'codigo_mh' => '18', 'departamento_id' => '4'],
            ['nombre' => 'Potonico', 'codigo_mh' => '19', 'departamento_id' => '4'],
            ['nombre' => 'San Antonio de la Cruz', 'codigo_mh' => '20', 'departamento_id' => '4'],
            ['nombre' => 'San Antonio Los Ranchos', 'codigo_mh' => '21', 'departamento_id' => '4'],
            ['nombre' => 'San Fernando', 'codigo_mh' => '22', 'departamento_id' => '4'],
            ['nombre' => 'San Francisco Lempa', 'codigo_mh' => '23', 'departamento_id' => '4'],
            ['nombre' => 'San Francisco Morazán', 'codigo_mh' => '24', 'departamento_id' => '4'],
            ['nombre' => 'San Ignacio', 'codigo_mh' => '25', 'departamento_id' => '4'],
            ['nombre' => 'San Isidro Labrador', 'codigo_mh' => '26', 'departamento_id' => '4'],
            ['nombre' => 'San José Cancasque', 'codigo_mh' => '27', 'departamento_id' => '4'],
            ['nombre' => 'San José Flores', 'codigo_mh' => '28', 'departamento_id' => '4'],
            ['nombre' => 'San Luis del Carmén', 'codigo_mh' => '29', 'departamento_id' => '4'],
            ['nombre' => 'San Miguel de Mercedes', 'codigo_mh' => '30', 'departamento_id' => '4'],
            ['nombre' => 'Santa Rafael', 'codigo_mh' => '31', 'departamento_id' => '4'],
            ['nombre' => 'Santa Rita', 'codigo_mh' => '32', 'departamento_id' => '4'],
            ['nombre' => 'Tejutla', 'codigo_mh' => '33', 'departamento_id' => '4'],
            ['nombre' => 'Antiguo Cuscatlán', 'codigo_mh' => '01', 'departamento_id' => '5'],
            ['nombre' => 'Ciudad Arce', 'codigo_mh' => '02', 'departamento_id' => '5'],
            ['nombre' => 'Colón', 'codigo_mh' => '03', 'departamento_id' => '5'],
            ['nombre' => 'Comasagua', 'codigo_mh' => '04', 'departamento_id' => '5'],
            ['nombre' => 'Chiltiupán', 'codigo_mh' => '05', 'departamento_id' => '5'],
            ['nombre' => 'Huizúcar', 'codigo_mh' => '06', 'departamento_id' => '5'],
            ['nombre' => 'Jayaque', 'codigo_mh' => '07', 'departamento_id' => '5'],
            ['nombre' => 'Jicalapa', 'codigo_mh' => '08', 'departamento_id' => '5'],
            ['nombre' => 'La Libertad', 'codigo_mh' => '09', 'departamento_id' => '5'],
            ['nombre' => 'Nuevo Cuscatlán', 'codigo_mh' => '10', 'departamento_id' => '5'],
            ['nombre' => 'Santa Tecla', 'codigo_mh' => '11', 'departamento_id' => '5'],
            ['nombre' => 'Quezaltepeque', 'codigo_mh' => '12', 'departamento_id' => '5'],
            ['nombre' => 'Sacacoyo', 'codigo_mh' => '13', 'departamento_id' => '5'],
            ['nombre' => 'San José Villanueva', 'codigo_mh' => '14', 'departamento_id' => '5'],
            ['nombre' => 'San Juan Opico', 'codigo_mh' => '15', 'departamento_id' => '5'],
            ['nombre' => 'San Matías', 'codigo_mh' => '16', 'departamento_id' => '5'],
            ['nombre' => 'San Pablo Tacachico', 'codigo_mh' => '17', 'departamento_id' => '5'],
            ['nombre' => 'Tamanique', 'codigo_mh' => '19', 'departamento_id' => '5'],
            ['nombre' => 'Talnique', 'codigo_mh' => '20', 'departamento_id' => '5'],
            ['nombre' => 'Teotepeque', 'codigo_mh' => '21', 'departamento_id' => '5'],
            ['nombre' => 'Tepecoyo', 'codigo_mh' => '22', 'departamento_id' => '5'],
            ['nombre' => 'Zaragoza', 'codigo_mh' => '23', 'departamento_id' => '5'],
            ['nombre' => 'Aguilares', 'codigo_mh' => '01', 'departamento_id' => '6'],
            ['nombre' => 'Apopa', 'codigo_mh' => '02', 'departamento_id' => '6'],
            ['nombre' => 'Ayutuxtepeque', 'codigo_mh' => '03', 'departamento_id' => '6'],
            ['nombre' => 'Cuscatancingo', 'codigo_mh' => '04', 'departamento_id' => '6'],
            ['nombre' => 'El Paisnal', 'codigo_mh' => '05', 'departamento_id' => '6'],
            ['nombre' => 'Guazapa', 'codigo_mh' => '06', 'departamento_id' => '6'],
            ['nombre' => 'Ilopango', 'codigo_mh' => '07', 'departamento_id' => '6'],
            ['nombre' => 'Mejicanos', 'codigo_mh' => '08', 'departamento_id' => '6'],
            ['nombre' => 'Nejapa', 'codigo_mh' => '09', 'departamento_id' => '6'],
            ['nombre' => 'Panchimalco', 'codigo_mh' => '10', 'departamento_id' => '6'],
            ['nombre' => 'Rosario de Mora', 'codigo_mh' => '11', 'departamento_id' => '6'],
            ['nombre' => 'San Marcos', 'codigo_mh' => '12', 'departamento_id' => '6'],
            ['nombre' => 'San Martín', 'codigo_mh' => '13', 'departamento_id' => '6'],
            ['nombre' => 'San Salvador', 'codigo_mh' => '14', 'departamento_id' => '6'],
            ['nombre' => 'Santiago Texacuangos', 'codigo_mh' => '15', 'departamento_id' => '6'],
            ['nombre' => 'Santo Tomás', 'codigo_mh' => '16', 'departamento_id' => '6'],
            ['nombre' => 'Soyapango', 'codigo_mh' => '17', 'departamento_id' => '6'],
            ['nombre' => 'Tonacatepeque', 'codigo_mh' => '18', 'departamento_id' => '6'],
            ['nombre' => 'Ciudad Delgado', 'codigo_mh' => '19', 'departamento_id' => '6'],
            ['nombre' => 'Candelaria', 'codigo_mh' => '01', 'departamento_id' => '7'],
            ['nombre' => 'Cojutepeque', 'codigo_mh' => '02', 'departamento_id' => '7'],
            ['nombre' => 'El Carmen', 'codigo_mh' => '03', 'departamento_id' => '7'],
            ['nombre' => 'El Rosario', 'codigo_mh' => '04', 'departamento_id' => '7'],
            ['nombre' => 'Monte San Juan', 'codigo_mh' => '05', 'departamento_id' => '7'],
            ['nombre' => 'Oratorio de Concepción', 'codigo_mh' => '06', 'departamento_id' => '7'],
            ['nombre' => 'San Bartolomé Perulapía', 'codigo_mh' => '07', 'departamento_id' => '7'],
            ['nombre' => 'San Cristóbal', 'codigo_mh' => '08', 'departamento_id' => '7'],
            ['nombre' => 'San Juan Guayabal', 'codigo_mh' => '09', 'departamento_id' => '7'],
            ['nombre' => 'San Pedro Perulapán', 'codigo_mh' => '10', 'departamento_id' => '7'],
            ['nombre' => 'San Rafael Cedros', 'codigo_mh' => '11', 'departamento_id' => '7'],
            ['nombre' => 'San Ramón', 'codigo_mh' => '12', 'departamento_id' => '7'],
            ['nombre' => 'Santa Cruz Analquito', 'codigo_mh' => '13', 'departamento_id' => '7'],
            ['nombre' => 'Santa Cruz Michapa', 'codigo_mh' => '14', 'departamento_id' => '7'],
            ['nombre' => 'Suchitoto', 'codigo_mh' => '15', 'departamento_id' => '7'],
            ['nombre' => 'Tenancingo', 'codigo_mh' => '16', 'departamento_id' => '7'],
            ['nombre' => 'Cuyultitán', 'codigo_mh' => '01', 'departamento_id' => '8'],
            ['nombre' => 'El Rosario', 'codigo_mh' => '02', 'departamento_id' => '8'],
            ['nombre' => 'Jerusalén', 'codigo_mh' => '03', 'departamento_id' => '8'],
            ['nombre' => 'Merced La Ceiba', 'codigo_mh' => '04', 'departamento_id' => '8'],
            ['nombre' => 'Olocuilta', 'codigo_mh' => '05', 'departamento_id' => '8'],
            ['nombre' => 'Paraíso de Osorio', 'codigo_mh' => '06', 'departamento_id' => '8'],
            ['nombre' => 'San Antonio Masahuat', 'codigo_mh' => '07', 'departamento_id' => '8'],
            ['nombre' => 'San Emigdio', 'codigo_mh' => '08', 'departamento_id' => '8'],
            ['nombre' => 'San Francisco Chinameca', 'codigo_mh' => '09', 'departamento_id' => '8'],
            ['nombre' => 'San Juan Nonualco', 'codigo_mh' => '10', 'departamento_id' => '8'],
            ['nombre' => 'San Juan Talpa', 'codigo_mh' => '11', 'departamento_id' => '8'],
            ['nombre' => 'San Juan Tepezontes', 'codigo_mh' => '12', 'departamento_id' => '8'],
            ['nombre' => 'San Luis Talpa', 'codigo_mh' => '13', 'departamento_id' => '8'],
            ['nombre' => 'San Miguel Tepezontes', 'codigo_mh' => '14', 'departamento_id' => '8'],
            ['nombre' => 'San Pedro Masahuat', 'codigo_mh' => '15', 'departamento_id' => '8'],
            ['nombre' => 'San Pedro Nonualco', 'codigo_mh' => '16', 'departamento_id' => '8'],
            ['nombre' => 'San Rafael Obrajuelo', 'codigo_mh' => '17', 'departamento_id' => '8'],
            ['nombre' => 'Santa María Ostuma', 'codigo_mh' => '18', 'departamento_id' => '8'],
            ['nombre' => 'Santiago Nonualco', 'codigo_mh' => '19', 'departamento_id' => '8'],
            ['nombre' => 'Tapalhuaca', 'codigo_mh' => '20', 'departamento_id' => '8'],
            ['nombre' => 'Zacatecoluca', 'codigo_mh' => '21', 'departamento_id' => '8'],
            ['nombre' => 'San Luis La Herradura', 'codigo_mh' => '22', 'departamento_id' => '8'],
            ['nombre' => 'Cinquera', 'codigo_mh' => '01', 'departamento_id' => '9'],
            ['nombre' => 'Guacotecti', 'codigo_mh' => '02', 'departamento_id' => '9'],
            ['nombre' => 'Ilobasco', 'codigo_mh' => '03', 'departamento_id' => '9'],
            ['nombre' => 'Jutiapa', 'codigo_mh' => '04', 'departamento_id' => '9'],
            ['nombre' => 'San Isidro', 'codigo_mh' => '05', 'departamento_id' => '9'],
            ['nombre' => 'Sensuntepeque', 'codigo_mh' => '06', 'departamento_id' => '9'],
            ['nombre' => 'Tejutepeque', 'codigo_mh' => '07', 'departamento_id' => '9'],
            ['nombre' => 'Victoria', 'codigo_mh' => '08', 'departamento_id' => '9'],
            ['nombre' => 'Dolores', 'codigo_mh' => '09', 'departamento_id' => '9'],
            ['nombre' => 'Apastepeque', 'codigo_mh' => '01', 'departamento_id' => '10'],
            ['nombre' => 'Guadalupe', 'codigo_mh' => '02', 'departamento_id' => '10'],
            ['nombre' => 'San Cayetano Istepeque', 'codigo_mh' => '03', 'departamento_id' => '10'],
            ['nombre' => 'Santa Clara', 'codigo_mh' => '04', 'departamento_id' => '10'],
            ['nombre' => 'Santo Domingo', 'codigo_mh' => '05', 'departamento_id' => '10'],
            ['nombre' => 'Santa Estefanía Catarina', 'codigo_mh' => '06', 'departamento_id' => '10'],
            ['nombre' => 'San Ildefonso', 'codigo_mh' => '07', 'departamento_id' => '10'],
            ['nombre' => 'San Lorenzo', 'codigo_mh' => '08', 'departamento_id' => '10'],
            ['nombre' => 'San Sebastián', 'codigo_mh' => '09', 'departamento_id' => '10'],
            ['nombre' => 'San Vicente', 'codigo_mh' => '10', 'departamento_id' => '10'],
            ['nombre' => 'Tecoluca', 'codigo_mh' => '11', 'departamento_id' => '10'],
            ['nombre' => 'Tepetitán', 'codigo_mh' => '12', 'departamento_id' => '10'],
            ['nombre' => 'Verapaz', 'codigo_mh' => '13', 'departamento_id' => '10'],
            ['nombre' => 'Alegría', 'codigo_mh' => '01', 'departamento_id' => '11'],
            ['nombre' => 'Berlín', 'codigo_mh' => '02', 'departamento_id' => '11'],
            ['nombre' => 'California', 'codigo_mh' => '03', 'departamento_id' => '11'],
            ['nombre' => 'Concepción Batres', 'codigo_mh' => '04', 'departamento_id' => '11'],
            ['nombre' => 'El Triunfo', 'codigo_mh' => '05', 'departamento_id' => '11'],
            ['nombre' => 'Ereguayquín', 'codigo_mh' => '06', 'departamento_id' => '11'],
            ['nombre' => 'Estanzuelas', 'codigo_mh' => '07', 'departamento_id' => '11'],
            ['nombre' => 'Jiquilisco', 'codigo_mh' => '08', 'departamento_id' => '11'],
            ['nombre' => 'Jucuapa', 'codigo_mh' => '09', 'departamento_id' => '11'],
            ['nombre' => 'Jucuarán', 'codigo_mh' => '10', 'departamento_id' => '11'],
            ['nombre' => 'Mercedes Umaña', 'codigo_mh' => '11', 'departamento_id' => '11'],
            ['nombre' => 'Nueva Granada', 'codigo_mh' => '12', 'departamento_id' => '11'],
            ['nombre' => 'Ozatlán', 'codigo_mh' => '13', 'departamento_id' => '11'],
            ['nombre' => 'Puerto El Triunfo', 'codigo_mh' => '14', 'departamento_id' => '11'],
            ['nombre' => 'San Agustín', 'codigo_mh' => '15', 'departamento_id' => '11'],
            ['nombre' => 'San Buenaventura', 'codigo_mh' => '16', 'departamento_id' => '11'],
            ['nombre' => 'San Dionisio', 'codigo_mh' => '17', 'departamento_id' => '11'],
            ['nombre' => 'Santa Elena', 'codigo_mh' => '18', 'departamento_id' => '11'],
            ['nombre' => 'San Francisco Javier', 'codigo_mh' => '19', 'departamento_id' => '11'],
            ['nombre' => 'Santa María', 'codigo_mh' => '20', 'departamento_id' => '11'],
            ['nombre' => 'Santiago de María', 'codigo_mh' => '21', 'departamento_id' => '11'],
            ['nombre' => 'Tecapán', 'codigo_mh' => '22', 'departamento_id' => '11'],
            ['nombre' => 'Usulután', 'codigo_mh' => '23', 'departamento_id' => '11'],
            ['nombre' => 'Carolina', 'codigo_mh' => '01', 'departamento_id' => '12'],
            ['nombre' => 'Ciudad Barrios', 'codigo_mh' => '02', 'departamento_id' => '12'],
            ['nombre' => 'Comacarán', 'codigo_mh' => '03', 'departamento_id' => '12'],
            ['nombre' => 'Chapeltique', 'codigo_mh' => '04', 'departamento_id' => '12'],
            ['nombre' => 'Chinameca', 'codigo_mh' => '05', 'departamento_id' => '12'],
            ['nombre' => 'Chirilagua', 'codigo_mh' => '06', 'departamento_id' => '12'],
            ['nombre' => 'El Tránsito', 'codigo_mh' => '07', 'departamento_id' => '12'],
            ['nombre' => 'Lolotique', 'codigo_mh' => '08', 'departamento_id' => '12'],
            ['nombre' => 'Moncagua', 'codigo_mh' => '09', 'departamento_id' => '12'],
            ['nombre' => 'Nueva Guadalupe', 'codigo_mh' => '10', 'departamento_id' => '12'],
            ['nombre' => 'Nuevo Edén de San Juan', 'codigo_mh' => '11', 'departamento_id' => '12'],
            ['nombre' => 'Quelepa', 'codigo_mh' => '12', 'departamento_id' => '12'],
            ['nombre' => 'San Antonio del Mosco', 'codigo_mh' => '13', 'departamento_id' => '12'],
            ['nombre' => 'San Gerardo', 'codigo_mh' => '14', 'departamento_id' => '12'],
            ['nombre' => 'San Jorge', 'codigo_mh' => '15', 'departamento_id' => '12'],
            ['nombre' => 'San Luis de la Reina', 'codigo_mh' => '16', 'departamento_id' => '12'],
            ['nombre' => 'San Miguel', 'codigo_mh' => '17', 'departamento_id' => '12'],
            ['nombre' => 'San Rafael Oriente', 'codigo_mh' => '18', 'departamento_id' => '12'],
            ['nombre' => 'Sesori', 'codigo_mh' => '19', 'departamento_id' => '12'],
            ['nombre' => 'Uluazapa', 'codigo_mh' => '20', 'departamento_id' => '12'],
            ['nombre' => 'Arambala', 'codigo_mh' => '01', 'departamento_id' => '13'],
            ['nombre' => 'Cacaopera', 'codigo_mh' => '02', 'departamento_id' => '13'],
            ['nombre' => 'Corinto', 'codigo_mh' => '03', 'departamento_id' => '13'],
            ['nombre' => 'Chilanga', 'codigo_mh' => '04', 'departamento_id' => '13'],
            ['nombre' => 'Delicias de Concepción', 'codigo_mh' => '05', 'departamento_id' => '13'],
            ['nombre' => 'El Divisadero', 'codigo_mh' => '06', 'departamento_id' => '13'],
            ['nombre' => 'El Rosario', 'codigo_mh' => '07', 'departamento_id' => '13'],
            ['nombre' => 'Gualococti', 'codigo_mh' => '08', 'departamento_id' => '13'],
            ['nombre' => 'Guatajiagua', 'codigo_mh' => '09', 'departamento_id' => '13'],
            ['nombre' => 'Joateca', 'codigo_mh' => '10', 'departamento_id' => '13'],
            ['nombre' => 'Jocoaitique', 'codigo_mh' => '11', 'departamento_id' => '13'],
            ['nombre' => 'Jocoro', 'codigo_mh' => '12', 'departamento_id' => '13'],
            ['nombre' => 'Lolotiquillo', 'codigo_mh' => '13', 'departamento_id' => '13'],
            ['nombre' => 'Meanguera', 'codigo_mh' => '14', 'departamento_id' => '13'],
            ['nombre' => 'Osicala', 'codigo_mh' => '15', 'departamento_id' => '13'],
            ['nombre' => 'Perquín', 'codigo_mh' => '16', 'departamento_id' => '13'],
            ['nombre' => 'San Carlos', 'codigo_mh' => '17', 'departamento_id' => '13'],
            ['nombre' => 'San Fernando', 'codigo_mh' => '18', 'departamento_id' => '13'],
            ['nombre' => 'San Francisco Gotera', 'codigo_mh' => '19', 'departamento_id' => '13'],
            ['nombre' => 'San Isidro', 'codigo_mh' => '20', 'departamento_id' => '13'],
            ['nombre' => 'San Simón', 'codigo_mh' => '21', 'departamento_id' => '13'],
            ['nombre' => 'Sensembra', 'codigo_mh' => '22', 'departamento_id' => '13'],
            ['nombre' => 'Sociedad', 'codigo_mh' => '23', 'departamento_id' => '13'],
            ['nombre' => 'Torola', 'codigo_mh' => '24', 'departamento_id' => '13'],
            ['nombre' => 'Yamabal', 'codigo_mh' => '25', 'departamento_id' => '13'],
            ['nombre' => 'Yoloaiquín', 'codigo_mh' => '26', 'departamento_id' => '13'],
            ['nombre' => 'Anamoros', 'codigo_mh' => '01', 'departamento_id' => '14'],
            ['nombre' => 'Bolívar', 'codigo_mh' => '02', 'departamento_id' => '14'],
            ['nombre' => 'Concepción de Oriente', 'codigo_mh' => '03', 'departamento_id' => '14'],
            ['nombre' => 'Conchagua', 'codigo_mh' => '04', 'departamento_id' => '14'],
            ['nombre' => 'El Carmen', 'codigo_mh' => '05', 'departamento_id' => '14'],
            ['nombre' => 'El Sauce', 'codigo_mh' => '06', 'departamento_id' => '14'],
            ['nombre' => 'Intipucá', 'codigo_mh' => '07', 'departamento_id' => '14'],
            ['nombre' => 'La Unión', 'codigo_mh' => '08', 'departamento_id' => '14'],
            ['nombre' => 'Lislique', 'codigo_mh' => '09', 'departamento_id' => '14'],
            ['nombre' => 'Meanguera del Golfo', 'codigo_mh' => '10', 'departamento_id' => '14'],
            ['nombre' => 'Nueva Esparta', 'codigo_mh' => '11', 'departamento_id' => '14'],
            ['nombre' => 'Pasaquina', 'codigo_mh' => '12', 'departamento_id' => '14'],
            ['nombre' => 'Polorós', 'codigo_mh' => '13', 'departamento_id' => '14'],
            ['nombre' => 'San Alejo', 'codigo_mh' => '14', 'departamento_id' => '14'],
            ['nombre' => 'San Jose', 'codigo_mh' => '15', 'departamento_id' => '14'],
            ['nombre' => 'Santa Rosa de Lima', 'codigo_mh' => '16', 'departamento_id' => '14'],
            ['nombre' => 'Yayantique', 'codigo_mh' => '17', 'departamento_id' => '14'],
            ['nombre' => 'Yucuaiquín', 'codigo_mh' => '18', 'departamento_id' => '14'],
        ];

        foreach ($municipios as $municipio) {
            Municipio::create([
                'nombre' => $municipio['nombre'],
                'codigo_mh' => $municipio['codigo_mh'],
                'departamento_id' => $municipio['departamento_id'],
                'user_id' => $users->random()->id
            ]);
        }
    }
}
